import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CirclePause, CirclePlay, Gauge, History, ListRestart, RotateCcw, SkipForward, Square, Trash2, WandSparkles } from 'lucide-react';

const API = import.meta.env.VITE_API_URL || '/api';
const labels = { stopped:'Detenido', prepared:'Preparado', simulating:'Simulando', paused:'Pausado', error:'Error', ready:'Listo', pending:'Pendiente', skipped:'Omitido', playing:'Ahora', done:'Simulado' };
const colors = { stopped:'text-slate-400', prepared:'text-cyan-300', simulating:'text-emerald-400', paused:'text-amber-300', error:'text-rose-400' };
const duration = value => `${Math.floor(Number(value||0)/60)}:${String(Math.floor(Number(value||0)%60)).padStart(2,'0')}`;
const time = value => value ? new Intl.DateTimeFormat('es-PA',{timeZone:'America/Panama',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(value)) : '—';

export default function Automation() {
  const [status,setStatus]=useState(null),[current,setCurrent]=useState(null),[queue,setQueue]=useState([]),[history,setHistory]=useState([]),[blocks,setBlocks]=useState([]),[clocks,setClocks]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[speed,setSpeed]=useState(20);
  const [form,setForm]=useState({scheduleBlockId:'',musicalClockId:'',testDateTime:''});
  const load=async()=>{try{const [s,c,q,h]=await Promise.all(['status','current','queue','history'].map(path=>fetch(`${API}/automation/${path}`).then(r=>r.ok?r.json():Promise.reject(new Error('Motor no disponible.')))));setStatus(s);setCurrent(c);setQueue(q);setHistory(h);setError('');}catch(e){setError(e.message);}};
  useEffect(()=>{load();Promise.all([fetch(`${API}/schedule`).then(r=>r.json()),fetch(`${API}/musical-clocks`).then(r=>r.json())]).then(([b,c])=>{setBlocks(b);setClocks(c);setForm(v=>({...v,scheduleBlockId:v.scheduleBlockId||String(b[0]?.id||''),musicalClockId:v.musicalClockId||String(b[0]?.musicalClockId||c[0]?.id||'')}));}).catch(()=>setError('No se pudieron cargar Programación y Relojes.'));const timer=setInterval(load,1000);return()=>clearInterval(timer);},[]);
  const action=async(path,body={})=>{setBusy(true);setError('');try{const response=await fetch(`${API}/automation/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error);await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const generate=(regenerate=false)=>action(regenerate?'regenerate':'generate',{...form,scheduleBlockId:Number(form.scheduleBlockId),musicalClockId:Number(form.musicalClockId),testDateTime:form.testDateTime||undefined,speed});
  const difference=useMemo(()=>queue.reduce((sum,item)=>sum+Number(item.duration||0),0)-(current?.block?((Number(current.block.endTime.slice(0,2))*60+Number(current.block.endTime.slice(3)))-(Number(current.block.startTime.slice(0,2))*60+Number(current.block.startTime.slice(3))))*60:0),[queue,current]);
  return <main className="space-y-5 p-5 pb-28 md:p-8">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="label">Simulación segura</div><h2 className="mt-1 text-2xl font-extrabold">Motor de Automatización</h2><p className="mt-1 text-sm text-slate-500">Genera y simula colas sin reproducir audio ni modificar AutoDJ.</p></div><div className="flex flex-wrap gap-2"><Select value={form.scheduleBlockId} onChange={e=>{const id=e.target.value;const block=blocks.find(b=>String(b.id)===id);setForm(v=>({...v,scheduleBlockId:id,musicalClockId:String(block?.musicalClockId||v.musicalClockId)}));}}>{blocks.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select><Select value={form.musicalClockId} onChange={e=>setForm(v=>({...v,musicalClockId:e.target.value}))}>{clocks.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><input type="datetime-local" value={form.testDateTime} onChange={e=>setForm(v=>({...v,testDateTime:e.target.value}))} className="rounded-xl border border-line bg-slate-950 px-3 py-2 text-xs"/><button disabled={busy||!form.scheduleBlockId||!form.musicalClockId} onClick={()=>generate(false)} className="rounded-xl bg-cyan-400 px-4 py-2 text-xs font-bold text-slate-950"><WandSparkles className="mr-2 inline" size={15}/>Generar</button></div></div>
    {error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</div>}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card label="Estado" value={labels[status?.status]||'Detenido'} icon={Gauge} accent={colors[status?.status]}/><Card label="Bloque actual" value={current?.block?.name||'Selección manual'} detail={current?.block?`${current.block.startTime}–${current.block.endTime}`:'Panamá · 24 horas'}/><Card label="Reloj asignado" value={current?.clock?.name||'Sin reloj'} detail={`${queue.length} elementos`}/><Card label="Ajuste del bloque" value={!queue.length?'Sin cola':difference===0?'Exacto':difference>0?`${duration(difference)} de exceso`:`${duration(Math.abs(difference))} faltantes`} accent={difference>0?'text-rose-300':'text-amber-300'}/></section>
    <section className="panel p-4"><div className="flex flex-wrap items-center gap-2"><Select value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[1,5,20,60].map(v=><option key={v} value={v}>Velocidad x{v}</option>)}</Select><Control icon={CirclePlay} text={status?.status==='paused'?'Reanudar':'Iniciar'} onClick={()=>action(status?.status==='paused'?'resume':'start-simulation',{speed})} disabled={!['prepared','paused'].includes(status?.status)}/><Control icon={CirclePause} text="Pausar" onClick={()=>action('pause')} disabled={status?.status!=='simulating'}/><Control icon={SkipForward} text="Saltar" onClick={()=>action('skip')} disabled={!['simulating','paused'].includes(status?.status)}/><Control icon={Square} text="Detener" onClick={()=>action('stop')} disabled={!status?.run}/><Control icon={RotateCcw} text="Regenerar" onClick={()=>generate(true)} disabled={!status?.run}/><Control icon={Trash2} text="Limpiar" onClick={()=>action('clear')} disabled={!status?.run}/></div></section>
    <section className="grid gap-5 xl:grid-cols-[1.65fr_1fr]"><div className="panel overflow-hidden"><Title icon={ListRestart}>Cola completa</Title>{!queue.length?<Empty text="Genera una simulación para construir la cola."/>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-950/40 text-slate-500"><tr>{['#','Hora','Tipo','Título / artista','Duración','Origen','Estado',''].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{queue.map((item,index)=><tr key={item.id} className={`border-t border-line ${item.id===status?.current?.id?'bg-cyan-400/[.06]':''}`}><td className="px-4 py-3 font-mono">{index+1}</td><td className="px-4 py-3 font-mono">{time(item.scheduledAt)}</td><td className="px-4 py-3">{item.type}</td><td className="px-4 py-3"><div className="font-semibold">{item.title}</div><div className="text-slate-500">{item.artist||item.warnings[0]||'—'}</div></td><td className="px-4 py-3 font-mono">{duration(item.duration)}</td><td className="px-4 py-3">{item.metadata.source}</td><td className="px-4 py-3"><span className="rounded-full bg-slate-800 px-2 py-1">{labels[item.status]||item.status}</span></td><td className="px-4 py-3"><button title="Marcar omitido" disabled={['done','skipped'].includes(item.status)} onClick={()=>fetch(`${API}/automation/queue/${item.id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'skipped'})}).then(load)}><SkipForward size={15}/></button></td></tr>)}</tbody></table></div>}</div>
      <div className="space-y-5"><div className="panel p-5"><div className="label">Ahora</div><div className="mt-3 text-lg font-bold">{status?.current?.title||'Sin elemento activo'}</div><div className="text-sm text-slate-500">{status?.current?.artist||labels[status?.status]}</div><div className="mt-4 h-2 rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-400" style={{width:status?.current?`${Math.min(100,((status.run?.simulatedElapsed||0)/Math.max(1,status.current.duration))*100)}%`:'0%'}}/></div><div className="mt-4 label">Siguiente</div><div className="mt-2 font-semibold">{status?.next?.title||'No disponible'}</div></div><div className="panel overflow-hidden"><Title icon={History}>Historial</Title>{!history.length?<Empty text="Los elementos simulados aparecerán aquí."/>:<div className="max-h-80 overflow-auto">{history.map(item=><div key={item.id} className="border-t border-line p-4 text-xs"><div className="flex justify-between"><b>{item.title}</b><span className="text-slate-500">{time(item.simulatedAt)}</span></div><div className="mt-1 text-slate-500">Planificado {time(item.plannedAt)} · {labels[item.result]||item.result}</div></div>)}</div>}</div></div></section>
    {queue.some(i=>i.warnings.length)&&<section className="panel p-5"><Title icon={AlertTriangle}>Advertencias</Title><div className="mt-3 space-y-2">{queue.flatMap(i=>i.warnings.map((w,n)=><p key={`${i.id}-${n}`} className="text-sm text-amber-300">{i.title}: {w}</p>))}</div></section>}
  </main>;
}
function Select({children,...props}){return <select {...props} className="rounded-xl border border-line bg-slate-950 px-3 py-2 text-xs">{children}</select>}
function Control({icon:Icon,text,...props}){return <button {...props} className="flex items-center gap-2 rounded-xl border border-line px-3 py-2 text-xs font-semibold text-slate-300 disabled:opacity-30"><Icon size={16}/>{text}</button>}
function Card({label,value,detail,icon:Icon,accent=''}){return <div className="panel p-5"><div className="label flex items-center gap-2">{Icon&&<Icon size={15}/>} {label}</div><div className={`mt-3 truncate text-xl font-bold ${accent}`}>{value}</div>{detail&&<div className="mt-1 text-xs text-slate-500">{detail}</div>}</div>}
function Title({icon:Icon,children}){return <div className="flex items-center gap-2 border-b border-line p-4 text-sm font-bold"><Icon size={17} className="text-cyan-400"/>{children}</div>}
function Empty({text}){return <div className="p-8 text-center text-sm text-slate-500">{text}</div>}
