import { useEffect, useRef, useState } from 'react';
import { ChevronDown, ChevronUp, Loader2, Pause, Play, Radio, Volume1, Volume2, VolumeX } from 'lucide-react';
import { LiveRadioController } from '../lib/liveRadioController.js';

const API = import.meta.env.VITE_API_URL || '/api';

export default function LiveRadioPlayer() {
  const [info, setInfo] = useState(null); const [expanded, setExpanded] = useState(false); const [message, setMessage] = useState('');
  const [state, setState] = useState({ status: 'Sin señal', playing: false, volume: .7, muted: false });
  const controllerRef = useRef(null);
  if (!controllerRef.current) controllerRef.current = new LiveRadioController({ audio: new Audio(), onState: setState });
  useEffect(() => { let mounted = true; const load = async () => { try { const response = await fetch(`${API}/azuracast/live-stream`); const text = await response.text(); let body; try { body = JSON.parse(text); } catch { throw new Error('Backend desconectado. Verifica el puerto 8091.'); } if (!response.ok) throw new Error(body.error); if (mounted) { setInfo(body); controllerRef.current.setSource(body.streamUrl); setMessage(''); } } catch (error) { if (mounted) { setMessage(error.message || 'No se pudo consultar la señal.'); setState(value => ({ ...value, status: 'Sin señal' })); } } }; load(); const timer = setInterval(load, 15000); return () => { mounted = false; clearInterval(timer); controllerRef.current?.pause(); }; }, []);
  const toggle = async () => { setMessage(''); if (state.playing || state.status === 'Conectando' || state.status === 'Reintentando') return controllerRef.current.pause(); try { await controllerRef.current.play(); } catch (error) { setMessage(error.name === 'NotAllowedError' ? 'El navegador bloqueó la reproducción. Pulsa Play nuevamente.' : error.message); } };
  const statusColor = state.status === 'En vivo' ? 'text-emerald-400' : state.status === 'Error' || state.status === 'Sin señal' ? 'text-rose-400' : 'text-amber-300';
  return <section className="fixed inset-x-0 bottom-0 z-40 border-t border-line bg-[#080d16]/95 shadow-2xl backdrop-blur-xl lg:left-64"><div className="flex min-h-20 items-center gap-3 px-4 md:px-6"><button onClick={toggle} disabled={!info?.online} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-cyan-400 text-slate-950 disabled:bg-slate-700 disabled:text-slate-500" aria-label={state.playing ? 'Pausar radio en vivo' : 'Reproducir radio en vivo'}>{state.status === 'Conectando' ? <Loader2 size={20} className="animate-spin"/> : state.playing ? <Pause size={20}/> : <Play size={20} className="ml-0.5"/>}</button>{info?.nowPlaying?.artwork ? <img src={info.nowPlaying.artwork} alt="" className="h-12 w-12 rounded-xl object-cover"/> : <div className="grid h-12 w-12 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><Radio/></div>}<div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className={`text-[10px] font-bold uppercase tracking-widest ${statusColor}`}>● {state.status}</span><span className="hidden text-[10px] text-slate-600 sm:inline">{info?.station || 'Panda Radio'}</span></div><div className="mt-1 truncate text-sm font-bold">{info?.nowPlaying?.title || 'Señal en vivo'}</div><div className="truncate text-xs text-slate-500">{info?.nowPlaying?.artist || message || 'Pulsa Play para escuchar'}</div></div><div className="hidden items-center gap-2 md:flex">{state.muted || state.volume === 0 ? <VolumeX size={17}/> : state.volume < .5 ? <Volume1 size={17}/> : <Volume2 size={17}/>}<input aria-label="Volumen" type="range" min="0" max="1" step=".01" value={state.volume} onChange={event => controllerRef.current.setVolume(event.target.value)} className="w-24 accent-cyan-400"/><button onClick={() => controllerRef.current.toggleMute()} className="rounded-lg border border-line px-2 py-1 text-[10px] text-slate-400">{state.muted ? 'Activar' : 'Silenciar'}</button></div><button onClick={() => setExpanded(value => !value)} className="rounded-lg p-2 text-slate-500" aria-label="Expandir reproductor">{expanded ? <ChevronDown/> : <ChevronUp/>}</button></div>{expanded && <div className="grid gap-3 border-t border-line px-5 py-4 text-xs sm:grid-cols-3"><Detail label="Estación" value={info?.station || 'No disponible'}/><Detail label="Oyentes actuales" value={info?.listeners ?? 0}/><Detail label="Origen" value="Stream público seguro de AzuraCast"/>{message && <p className="text-rose-300 sm:col-span-3">{message}</p>}<div className="flex items-end gap-1 sm:col-span-3">{Array.from({length:24},(_,index)=><i key={index} className={`w-1 rounded-full ${state.playing?'animate-pulse bg-cyan-400':'bg-slate-700'}`} style={{height:`${6+(index%7)*3}px`,animationDelay:`${index*40}ms`}}/>)}</div></div>}</section>;
}
function Detail({label,value}){return <div><div className="label">{label}</div><div className="mt-1 truncate font-semibold text-slate-300">{value}</div></div>}
