import { useEffect,useMemo,useRef,useState } from 'react';
import { ArrowDown,ArrowUp,Copy,Disc3,GripVertical,Library,Lock,Pause,Play,Plus,RotateCcw,Save,Search,SkipForward,Square,Trash2,Unlock,Volume2,Wand2 } from 'lucide-react';
import { LiveAssistPlayback } from '../lib/liveAssistPlayback.js';
const API=import.meta.env.VITE_API_URL||'/api';
const colors={playing:'border-emerald-400/50 bg-emerald-400/10',next:'border-amber-400/50 bg-amber-400/10',pending:'border-cyan-400/20 bg-cyan-400/[.04]',played:'border-rose-400/30 bg-rose-400/[.06]',skipped:'border-slate-600 bg-slate-800/40',error:'border-orange-400/40 bg-orange-400/10'};
const fmt=n=>`${Math.floor(Number(n||0)/60)}:${String(Math.floor(Number(n||0)%60)).padStart(2,'0')}`;
const clock=v=>v?new Intl.DateTimeFormat('es-PA',{timeZone:'America/Panama',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(v)):'—';
export default function LiveAssist(){
 const [queue,setQueue]=useState(null),[media,setMedia]=useState([]),[cartwall,setCartwall]=useState([]),[playlists,setPlaylists]=useState([]),[query,setQuery]=useState(''),[genre,setGenre]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[playlistName,setPlaylistName]=useState('Mi playlist'),[playback,setPlayback]=useState({status:'stopped',currentTime:0,duration:0,volume:.8}),[repeat,setRepeat]=useState(false),[manual,setManual]=useState(false);
 const controller=useRef(),dragId=useRef();
 const api=async(path,options={})=>{const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const body=await r.json();if(!r.ok)throw new Error(body.error||'Operación no disponible.');return body};
 const load=async()=>{try{const [q,p]=await Promise.all([api('/live-assist/queue'),api('/saved-playlists')]);setQueue(q);setPlaylists(p);setError('');}catch(e){setError(e.message)}};
 const playItem=async item=>{try{await api(`/live-assist/queue/items/${item.id}/status`,{method:'PATCH',body:JSON.stringify({status:'playing'})});await controller.current.play(item);await load()}catch(e){setError(e.message)}};
 useEffect(()=>{controller.current=new LiveAssistPlayback({audio:new Audio(),onState:setPlayback,onEnded:async info=>{try{if(repeat){await controller.current.restart();return}const q=await api('/live-assist/queue/next',{method:'POST',body:JSON.stringify(info)});setQueue(q);if(q.current&&!q.stopAfterCurrent)await controller.current.play(q.current)}catch(e){setError(e.message)}},onError:async()=>{setError('El navegador no pudo reproducir este elemento.');if(controller.current.item)await api(`/live-assist/queue/items/${controller.current.item.id}/status`,{method:'PATCH',body:JSON.stringify({status:'error'})});}});load();Promise.all([api('/azuracast/media'),api('/cartwall')]).then(([m,c])=>{setMedia(m);setCartwall(c)}).catch(e=>setError(e.message));return()=>controller.current?.dispose()},[]);
 const genres=useMemo(()=>[...new Set(media.map(x=>x.genre).filter(Boolean))].sort(),[media]);const filtered=useMemo(()=>media.filter(x=>(!query||`${x.title} ${x.artist} ${x.album}`.toLowerCase().includes(query.toLowerCase()))&&(!genre||x.genre===genre)).slice(0,250),[media,query,genre]);
 const add=async(track,position)=>{try{await api('/live-assist/queue/items',{method:'POST',body:JSON.stringify({position,mediaId:track.id,type:'Música',title:track.title||track.path,artist:track.artist||'',duration:track.duration,metadata:{artwork:track.artwork,album:track.album,genre:track.genre}})});await load()}catch(e){setError(e.message)}};
 const command=async(path,body={})=>{try{const q=await api(path,{method:'POST',body:JSON.stringify(body)});if(q?.items)setQueue(q);else await load()}catch(e){setError(e.message)}};
 const update=async(item,body)=>{try{await api(`/live-assist/queue/items/${item.id}`,{method:'PUT',body:JSON.stringify(body)});await load()}catch(e){setError(e.message)}};
 const remove=async item=>{try{await api(`/live-assist/queue/items/${item.id}`,{method:'DELETE'});await load()}catch(e){setError(e.message)}};
 const reorder=async(ids)=>{try{setQueue(q=>({...q,items:ids.map(id=>q.items.find(x=>x.id===id))}));await command('/live-assist/queue/reorder',{itemIds:ids})}catch(e){setError(e.message)}};
 const move=(item,delta)=>{const ids=queue.items.map(x=>x.id),from=ids.indexOf(item.id),to=from+delta;if(to<0||to>=ids.length)return;[ids[from],ids[to]]=[ids[to],ids[from]];reorder(ids)};
 const next=async()=>{controller.current.stop();await command('/live-assist/queue/next',{actualDuration:playback.currentTime});await load();const fresh=await api('/live-assist/queue');setQueue(fresh);if(fresh.current&&!manual)controller.current.play(fresh.current).catch(e=>setError(e.message))};
 const stop=async()=>{controller.current.stop();try{setQueue(await api('/live-assist/queue',{method:'PATCH',body:JSON.stringify({status:'stopped'})}))}catch(e){setError(e.message)}};
 const save=async()=>{setSaving(true);try{await api('/saved-playlists',{method:'POST',body:JSON.stringify({name:playlistName,description:'Creada desde Live Assist',color:'#22d3ee',active:true})});await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 return <main className="p-4 pb-32 md:p-6"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><div className="label">Operación local</div><h2 className="text-2xl font-extrabold">Operador / Live Assist</h2><p className="text-xs text-slate-500">Audio local de monitoreo · no sale al aire</p></div><div className="flex gap-2"><input value={playlistName} onChange={e=>setPlaylistName(e.target.value)} className="rounded-xl border border-line bg-slate-950 px-3 py-2 text-xs"/><button onClick={save} disabled={saving||!queue?.items.length} className="rounded-xl bg-cyan-400 px-3 py-2 text-xs font-bold text-slate-950"><Save size={15} className="mr-1 inline"/>Guardar playlist</button></div></div>{error&&<div className="mb-4 rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</div>}
 <div className="mb-3 flex flex-wrap justify-end gap-2 text-xs"><button onClick={stop} className="rounded-lg border border-line px-3 py-2"><Square size={14} className="mr-1 inline"/>Detener cola</button><button disabled={!queue?.current} onClick={()=>queue?.current&&api(`/live-assist/queue/items/${queue.current.id}/status`,{method:'PATCH',body:JSON.stringify({status:'skipped'})}).then(setQueue)} className="rounded-lg border border-line px-3 py-2 disabled:opacity-30"><SkipForward size={14} className="mr-1 inline"/>Omitir actual</button><button onClick={()=>command('/live-assist/queue/clear')} className="rounded-lg border border-rose-500/30 px-3 py-2 text-rose-300"><Trash2 size={14} className="mr-1 inline"/>Vaciar cola</button></div>
 <section className="grid min-h-[65vh] gap-4 xl:grid-cols-[1.05fr_1.4fr_.85fr]">
  <div className="panel overflow-hidden"><Head icon={Library} title="Biblioteca Musical" detail={`${media.length} pistas`}/><div className="grid grid-cols-[1fr_auto] gap-2 border-b border-line p-3"><label className="flex items-center gap-2 rounded-lg border border-line bg-slate-950 px-3"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar..." className="w-full bg-transparent py-2 text-xs"/></label><select value={genre} onChange={e=>setGenre(e.target.value)} className="rounded-lg border border-line bg-slate-950 px-2 text-xs"><option value="">Géneros</option>{genres.map(g=><option key={g}>{g}</option>)}</select></div><div className="max-h-[62vh] overflow-auto">{filtered.map(track=><div key={track.id} draggable onDragStart={()=>dragId.current=track.id} onDoubleClick={()=>add(track)} className="group flex cursor-grab items-center gap-2 border-b border-line/60 p-2 hover:bg-white/[.04]"><GripVertical size={14} className="text-slate-700"/><div className="min-w-0 flex-1"><div className="truncate text-xs font-semibold">{track.title}</div><div className="truncate text-[10px] text-slate-500">{track.artist||'Sin artista'} · {track.genre||'Sin género'}</div></div><span className="font-mono text-[10px] text-slate-600">{fmt(track.duration)}</span><button title="Insertar siguiente" onClick={()=>add(track,(queue?.current?.position??-1)+1)} className="opacity-0 group-hover:opacity-100"><Plus size={15}/></button><button title="Reproducir ahora local" onClick={async()=>{const item=await api('/live-assist/queue/items',{method:'POST',body:JSON.stringify({position:0,mediaId:track.id,type:'Música',title:track.title,artist:track.artist,duration:track.duration,metadata:{artwork:track.artwork}})});await playItem(item)}} className="opacity-0 group-hover:opacity-100"><Play size={15}/></button></div>)}</div></div>
  <div className="panel overflow-hidden" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const track=media.find(x=>x.id===dragId.current);if(track)add(track)}}><Head icon={Disc3} title="Cola de reproducción" detail={`${queue?.items.length||0} elementos · ${fmt(queue?.totalDuration)}`}/>{!queue?.items.length?<div className="grid min-h-80 place-items-center text-center text-sm text-slate-500"><div><Wand2 className="mx-auto mb-3"/>Arrastra canciones aquí<br/>o haz doble clic en la biblioteca.</div></div>:<div className="max-h-[62vh] overflow-auto p-2">{queue.items.map((item,index)=>{const visual=item.id===queue.current?.id?'playing':item.id===queue.next?.id?'next':item.status;return <div key={item.id} draggable={!item.locked} onDragStart={()=>dragId.current=`q:${item.id}`} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(String(dragId.current).startsWith('q:')){const source=Number(String(dragId.current).slice(2)),ids=queue.items.map(x=>x.id),from=ids.indexOf(source),to=ids.indexOf(item.id);ids.splice(to,0,ids.splice(from,1)[0]);reorder(ids)}}} className={`mb-1 flex items-center gap-2 rounded-lg border p-2 ${colors[visual]||colors.pending}`}><GripVertical size={14}/><span className="w-6 font-mono text-[10px] text-slate-500">{index+1}</span><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold">{item.title}</div><div className="truncate text-[10px] text-slate-500">{item.artist||item.type} · {clock(item.scheduledAt)}</div>{visual==='playing'&&<div className="mt-1 h-1 rounded bg-slate-800"><div className="h-full rounded bg-emerald-400" style={{width:`${Math.min(100,(playback.currentTime/Math.max(1,playback.duration))*100)}%`}}/></div>}</div><span className="font-mono text-[10px]">{fmt(item.duration)}</span><div className="flex gap-1 text-slate-500"><button onClick={()=>move(item,-1)}><ArrowUp size={13}/></button><button onClick={()=>move(item,1)}><ArrowDown size={13}/></button><button onClick={()=>update(item,{locked:!item.locked})}>{item.locked?<Lock size={13}/>:<Unlock size={13}/>}</button><button onClick={()=>command(`/live-assist/queue/items/${item.id}/duplicate`)}><Copy size={13}/></button><button onClick={()=>remove(item)}><Trash2 size={13}/></button></div></div>})}</div>}</div>
  <div className="space-y-4"><div className="panel overflow-hidden"><Head icon={Volume2} title="Ahora sonando" detail="Reproducción local"/><div className="p-5 text-center"><div className="mx-auto grid h-36 w-36 place-items-center overflow-hidden rounded-2xl bg-gradient-to-br from-cyan-500/20 to-violet-500/20">{queue?.current?.metadata?.artwork?<img src={queue.current.metadata.artwork} className="h-full w-full object-cover"/>:<Disc3 size={48}/>}</div><div className="mt-4 truncate text-lg font-bold">{queue?.current?.title||'Sin reproducción'}</div><div className="truncate text-sm text-slate-500">{queue?.current?.artist||'Añade pistas a la cola'}</div><div className="mt-4 h-2 rounded bg-slate-800"><div className="h-full rounded bg-cyan-400" style={{width:`${Math.min(100,(playback.currentTime/Math.max(1,playback.duration))*100)}%`}}/></div><div className="mt-2 flex justify-between font-mono text-[10px] text-slate-500"><span>{fmt(playback.currentTime)}</span><span>{fmt(playback.duration)}</span></div><div className="mt-4 flex justify-center gap-2"><Ctl icon={Play} onClick={()=>queue?.current?controller.current.play(queue.current):queue?.next&&playItem(queue.next)}/><Ctl icon={Pause} onClick={()=>controller.current.pause()}/><Ctl icon={Square} onClick={()=>controller.current.stop()}/><Ctl icon={SkipForward} onClick={next}/><Ctl icon={RotateCcw} onClick={()=>controller.current.restart()}/></div><div className="mt-3 flex items-center gap-2"><Volume2 size={14}/><input type="range" min="0" max="1" step=".01" value={playback.volume} onChange={e=>controller.current.setVolume(e.target.value)} className="w-full accent-cyan-400"/></div><div className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><Toggle value={!manual} onClick={()=>{setManual(v=>!v);api('/live-assist/queue',{method:'PATCH',body:JSON.stringify({autoAdvance:manual})}).then(setQueue)}} label={manual?'Manual':'Automático local'}/><Toggle value={repeat} onClick={()=>setRepeat(v=>!v)} label="Repetir"/><Toggle value={queue?.stopAfterCurrent} onClick={()=>api('/live-assist/queue',{method:'PATCH',body:JSON.stringify({stopAfterCurrent:!queue.stopAfterCurrent})}).then(setQueue)} label="Detener después"/><button onClick={()=>controller.current.fade()} className="rounded-lg border border-line p-2">Fade local</button></div></div></div>
  <div className="panel overflow-hidden"><Head icon={Save} title="Playlists guardadas" detail={`${playlists.length}`}/><div className="max-h-40 overflow-auto">{playlists.map(p=><div key={p.id} className="flex items-center gap-2 border-t border-line p-3 text-xs"><i className="h-2 w-2 rounded-full" style={{background:p.color}}/><div className="min-w-0 flex-1 truncate">{p.name}</div><span>{fmt(p.totalDuration)}</span><button onClick={()=>command(`/saved-playlists/${p.id}/load`)}><Play size={14}/></button><button onClick={()=>command(`/saved-playlists/${p.id}/duplicate`)}><Copy size={14}/></button><button onClick={async()=>{await api(`/saved-playlists/${p.id}`,{method:'DELETE'});load()}}><Trash2 size={14}/></button></div>)}</div></div>
  <div className="panel overflow-hidden"><Head icon={SkipForward} title="Insertar cartucho" detail="Jingles y comerciales"/><select onChange={e=>{const c=cartwall.find(x=>String(x.id)===e.target.value);if(c)command('/live-assist/queue/items',{mediaId:c.mediaId,cartwallButtonId:c.id,type:c.type,title:c.name,artist:'',duration:c.duration,metadata:{audioUrl:c.audioUrl}})}} className="m-3 w-[calc(100%-1.5rem)] rounded-lg border border-line bg-slate-950 p-2 text-xs"><option value="">Seleccionar...</option>{cartwall.filter(c=>c.active&&(c.mediaId||c.audioUrl)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div></div>
 </section></main>;
}
function Head({icon:Icon,title,detail}){return <div className="flex items-center gap-2 border-b border-line p-3"><Icon size={16} className="text-cyan-400"/><b className="text-sm">{title}</b><span className="ml-auto text-[10px] text-slate-500">{detail}</span></div>}
function Ctl({icon:Icon,...p}){return <button {...p} className="grid h-10 w-10 place-items-center rounded-full border border-line bg-slate-950 hover:border-cyan-400"><Icon size={17}/></button>}
function Toggle({value,label,...p}){return <button {...p} className={`rounded-lg border p-2 ${value?'border-cyan-400/40 bg-cyan-400/10 text-cyan-300':'border-line text-slate-500'}`}>{label}</button>}
