export const cartwallTypes=['Jingle','Comercial','ID de emisora','Promo','Sweep','Efecto','LocuciÃ³n','Noticia','Hora','Emergencia','Otro'];
export const cartwallHotkeys=[...Array.from({length:12},(_,i)=>`F${i+1}`),...Array.from({length:8},(_,i)=>`Shift+F${i+1}`)];
const HEX=/^#[0-9a-f]{6}$/i;
export class CartwallError extends Error{constructor(message,status=400,details={}){super(message);this.status=status;this.details=details;}}
export class CartwallNotFoundError extends CartwallError{constructor(){super('Cartucho no encontrado.',404);}}
const dto=row=>({id:row.id,slotNumber:row.slot_number,name:row.name,description:row.description,type:row.type,color:row.color,hotkey:row.hotkey,mediaId:row.media_id,audioUrl:row.audio_url,duration:Number(row.duration||0),volume:Number(row.volume),fadeIn:Number(row.fade_in||0),fadeOut:Number(row.fade_out||0),loop:Boolean(row.loop),allowOverlap:Boolean(row.allow_overlap),active:Boolean(row.active),createdAt:row.created_at,updatedAt:row.updated_at});
export class CartwallService{
 constructor(database){this.db=database;} async list(){return(await this.db.all('SELECT * FROM cartwall_buttons ORDER BY slot_number')).map(dto);} async get(id){const row=(await this.db.all('SELECT * FROM cartwall_buttons WHERE id=?',[id]))[0];if(!row)throw new CartwallNotFoundError();return dto(row);}
 normalize(input={},existing={}){const own=key=>Object.prototype.hasOwnProperty.call(input,key);const v={slotNumber:Number(input.slotNumber??existing.slotNumber),name:String(input.name??existing.name??'').trim(),description:String(input.description??existing.description??'').trim(),type:String(input.type??existing.type??'Otro'),color:String(input.color??existing.color??'#22d3ee'),hotkey:(own('hotkey')?input.hotkey:existing.hotkey)||null,mediaId:(own('mediaId')?input.mediaId:existing.mediaId)||null,audioUrl:String((own('audioUrl')?input.audioUrl:existing.audioUrl)||'').trim()||null,duration:Number(input.duration??existing.duration??0),volume:Number(input.volume??existing.volume??1),fadeIn:Number(input.fadeIn??existing.fadeIn??0),fadeOut:Number(input.fadeOut??existing.fadeOut??0),loop:input.loop===undefined?Boolean(existing.loop):Boolean(input.loop),allowOverlap:input.allowOverlap===undefined?Boolean(existing.allowOverlap):Boolean(input.allowOverlap),active:input.active===undefined?(existing.active??true):Boolean(input.active)};const d={};if(!Number.isInteger(v.slotNumber)||v.slotNumber<1||v.slotNumber>20)d.slotNumber='El slot debe estar entre 1 y 20.';if(!v.name&&(v.mediaId||v.audioUrl))d.name='El nombre es obligatorio cuando existe contenido.';if(!cartwallTypes.includes(v.type))d.type='El tipo no estÃ¡ permitido.';if(!HEX.test(v.color))d.color='El color debe ser hexadecimal.';if(v.hotkey&&!cartwallHotkeys.includes(v.hotkey))d.hotkey='La tecla no estÃ¡ permitida.';if(!Number.isFinite(v.volume)||v.volume<0||v.volume>1)d.volume='El volumen debe estar entre 0 y 1.';for(const key of ['duration','fadeIn','fadeOut'])if(!Number.isFinite(v[key])||v[key]<0)d[key]='El valor no puede ser negativo.';if(v.audioUrl&&!v.audioUrl.startsWith('/api/cartwall/media/')){try{const url=new URL(v.audioUrl);if(!['http:','https:'].includes(url.protocol))throw new Error();}catch{d.audioUrl='Usa una URL HTTP o HTTPS vÃ¡lida.';}}if(v.mediaId!==null&&!String(v.mediaId).trim())d.mediaId='La referencia multimedia no es vÃ¡lida.';if(Object.keys(d).length)throw new CartwallError('Revisa los datos del cartucho.',400,d);return v;}
 async unique(v,exclude=null){const slot=await this.db.all('SELECT id FROM cartwall_buttons WHERE slot_number=? AND id!=?',[v.slotNumber,exclude||-1]);if(slot.length)throw new CartwallError('Ese slot ya estÃ¡ ocupado.',409,{slotNumber:'Selecciona un slot libre.'});if(v.hotkey&&(await this.db.all('SELECT id FROM cartwall_buttons WHERE hotkey=? AND id!=?',[v.hotkey,exclude||-1])).length)throw new CartwallError('Esa tecla rÃ¡pida ya estÃ¡ asignada.',409,{hotkey:'Selecciona otra tecla.'});}
 params(v){return[v.slotNumber,v.name,v.description,v.type,v.color,v.hotkey,v.mediaId,v.audioUrl,v.duration,v.volume,v.fadeIn,v.fadeOut,v.loop?1:0,v.allowOverlap?1:0,v.active?1:0];}
 async create(input){const v=this.normalize(input);await this.unique(v);const result=await this.db.run('INSERT INTO cartwall_buttons (slot_number,name,description,type,color,hotkey,media_id,audio_url,duration,volume,fade_in,fade_out,loop,allow_overlap,active) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',this.params(v));return this.get(result.id);}
 async update(id,input){const current=await this.get(id),v=this.normalize(input,current);await this.unique(v,id);await this.db.run('UPDATE cartwall_buttons SET slot_number=?,name=?,description=?,type=?,color=?,hotkey=?,media_id=?,audio_url=?,duration=?,volume=?,fade_in=?,fade_out=?,loop=?,allow_overlap=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[...this.params(v),id]);return this.get(id);}
 async remove(id){await this.get(id);await this.db.run('DELETE FROM cartwall_buttons WHERE id=?',[id]);return{deleted:true,id};}
 async duplicate(id,input={}){const source=await this.get(id),rows=await this.db.all('SELECT * FROM cartwall_buttons ORDER BY slot_number');let target=input.slotNumber?rows.find(row=>row.slot_number===Number(input.slotNumber)):rows.find(row=>!row.active&&!row.audio_url&&!row.media_id&&/^CART \d{2}$/.test(row.name));const payload={...source,name:input.name||`${source.name} (copia)`,hotkey:input.hotkey||null,active:false};if(target)return this.update(target.id,{...payload,slotNumber:target.slot_number});const used=rows.map(row=>row.slot_number),slot=Number(input.slotNumber)||Array.from({length:20},(_,i)=>i+1).find(n=>!used.includes(n));if(!slot)throw new CartwallError('No hay slots libres para duplicar.',409);return this.create({...payload,slotNumber:slot});}
 async status(id,active){if(typeof active!=='boolean')throw new CartwallError('El estado debe usar true o false.');return this.update(id,{active});}
 async clear(id){const c=await this.get(id);return this.update(id,{name:`CART ${String(c.slotNumber).padStart(2,'0')}`,description:'',type:'Otro',color:'#334155',hotkey:c.hotkey,mediaId:null,audioUrl:null,duration:0,volume:1,fadeIn:0,fadeOut:0,loop:false,allowOverlap:false,active:false});}
}
