const parse = value => { try { return JSON.parse(value || '{}'); } catch { return {}; } };
const itemDto = row => row ? ({ id:row.id,queueId:row.queue_id,position:row.position,mediaId:row.media_id,cartwallButtonId:row.cartwall_button_id,type:row.item_type,title:row.title,artist:row.artist,duration:Number(row.duration||0),status:row.status,scheduledAt:row.scheduled_at,locked:Boolean(row.locked),metadata:parse(row.metadata_json),createdAt:row.created_at,updatedAt:row.updated_at }) : null;
const playlistDto = row => row ? ({ id:row.id,name:row.name,description:row.description,color:row.color,active:Boolean(row.active),totalDuration:Number(row.total_duration||0),createdAt:row.created_at,updatedAt:row.updated_at }) : null;
export class LiveAssistError extends Error { constructor(message,status=400,details={}){super(message);this.status=status;this.details=details;} }

export class LiveAssistService {
  constructor(db){this.db=db;}
  async queueRow(){let row=(await this.db.all('SELECT * FROM live_assist_queues ORDER BY id LIMIT 1'))[0];if(!row){const result=await this.db.run("INSERT INTO live_assist_queues (name) VALUES ('Cola principal')");row=(await this.db.all('SELECT * FROM live_assist_queues WHERE id=?',[result.id]))[0];}return row;}
  async getQueue(){const queue=await this.queueRow();const items=(await this.db.all('SELECT * FROM live_assist_queue_items WHERE queue_id=? ORDER BY position,id',[queue.id])).map(itemDto);const current=items.find(i=>i.id===queue.current_item_id)||items.find(i=>i.status==='playing')||null;const next=items.find(i=>i.position>(current?.position??-1)&&i.status==='pending')||items.find(i=>i.status==='pending')||null;return {id:queue.id,name:queue.name,status:queue.status,currentItemId:queue.current_item_id,autoAdvance:Boolean(queue.auto_advance),stopAfterCurrent:Boolean(queue.stop_after_current),items,current,next,totalDuration:items.filter(i=>!['played','skipped'].includes(i.status)).reduce((s,i)=>s+i.duration,0),history:await this.history()};}
  normalize(input,existing={}){const value={mediaId:input.mediaId??existing.mediaId??null,cartwallButtonId:input.cartwallButtonId??existing.cartwallButtonId??null,type:String(input.type??existing.type??'Música'),title:String(input.title??existing.title??'').trim(),artist:String(input.artist??existing.artist??'').trim(),duration:Number(input.duration??existing.duration??0),status:String(input.status??existing.status??'pending'),locked:input.locked===undefined?Boolean(existing.locked):Boolean(input.locked),metadata:input.metadata??existing.metadata??{}};const details={};if(!value.title)details.title='El título es obligatorio.';if(!Number.isFinite(value.duration)||value.duration<0)details.duration='La duración no es válida.';if(!value.mediaId&&!value.cartwallButtonId)details.source='Selecciona una pista o cartucho.';if(Object.keys(details).length)throw new LiveAssistError('Revisa el elemento.',400,details);return value;}
  async getItem(id){const row=(await this.db.all('SELECT * FROM live_assist_queue_items WHERE id=?',[id]))[0];if(!row)throw new LiveAssistError('Elemento no encontrado.',404);return itemDto(row);}
  async addItem(input){const queue=await this.queueRow();const value=this.normalize(input);if(input.allowDuplicate===false&&value.mediaId&&(await this.db.all('SELECT id FROM live_assist_queue_items WHERE queue_id=? AND media_id=? AND status NOT IN (\'played\',\'skipped\')',[queue.id,value.mediaId])).length)throw new LiveAssistError('La pista ya está en la cola.',409);const count=(await this.db.all('SELECT COUNT(*) count FROM live_assist_queue_items WHERE queue_id=?',[queue.id]))[0].count;const requested=input.position===undefined?count:Number(input.position);if(!Number.isInteger(requested)||requested<0||requested>count)throw new LiveAssistError('La posición no es válida.');await this.shift(queue.id,requested,1);const result=await this.db.run(`INSERT INTO live_assist_queue_items (queue_id,position,media_id,cartwall_button_id,item_type,title,artist,duration,status,locked,metadata_json) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,[queue.id,requested,value.mediaId,value.cartwallButtonId,value.type,value.title,value.artist,value.duration,value.status,value.locked?1:0,JSON.stringify(value.metadata)]);await this.recalculate(queue.id);return this.getItem(result.id);}
  async updateItem(id,input){const current=await this.getItem(id);if(current.locked&&input.locked!==false)throw new LiveAssistError('Desbloquea el elemento antes de modificarlo.',409);const value=this.normalize(input,current);await this.db.run('UPDATE live_assist_queue_items SET media_id=?,cartwall_button_id=?,item_type=?,title=?,artist=?,duration=?,status=?,locked=?,metadata_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[value.mediaId,value.cartwallButtonId,value.type,value.title,value.artist,value.duration,value.status,value.locked?1:0,JSON.stringify(value.metadata),id]);await this.recalculate(current.queueId);return this.getItem(id);}
  async removeItem(id){const item=await this.getItem(id);if(item.locked)throw new LiveAssistError('Desbloquea el elemento antes de eliminarlo.',409);await this.db.run('DELETE FROM live_assist_queue_items WHERE id=?',[id]);await this.normalizePositions(item.queueId);return {deleted:true,id};}
  async reorder(ids){const queue=await this.queueRow();const items=(await this.db.all('SELECT id,locked,position FROM live_assist_queue_items WHERE queue_id=? ORDER BY position',[queue.id]));if(!Array.isArray(ids)||ids.length!==items.length||new Set(ids).size!==ids.length||!items.every(i=>ids.includes(i.id)))throw new LiveAssistError('El orden debe contener todos los elementos una vez.');for(const locked of items.filter(i=>i.locked))if(ids.indexOf(locked.id)!==locked.position)throw new LiveAssistError('Los elementos bloqueados no pueden moverse.',409);await this.db.run('UPDATE live_assist_queue_items SET position=-(position+1) WHERE queue_id=?',[queue.id]);for(const [position,id] of ids.entries())await this.db.run('UPDATE live_assist_queue_items SET position=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[position,id]);await this.recalculate(queue.id);return (await this.getQueue()).items;}
  async duplicate(id){const item=await this.getItem(id);return this.addItem({...item,position:item.position+1,status:'pending',locked:false});}
  async setStatus(id,status,input={}){if(!['pending','playing','played','skipped','error'].includes(status))throw new LiveAssistError('Estado no permitido.');const item=await this.getItem(id);if(status==='playing'){await this.db.run("UPDATE live_assist_queue_items SET status='pending' WHERE queue_id=? AND status='playing'",[item.queueId]);await this.db.run("UPDATE live_assist_queues SET status='playing',current_item_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",[id,item.queueId]);}await this.db.run('UPDATE live_assist_queue_items SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[status,id]);if(['played','skipped','error'].includes(status))await this.record(item,status,input.actualDuration,input.startedAt);await this.recalculate(item.queueId);return this.getQueue();}
  async next(input={}){const queue=await this.queueRow();const current=queue.current_item_id?(await this.db.all('SELECT * FROM live_assist_queue_items WHERE id=?',[queue.current_item_id]))[0]:null;if(current){await this.db.run("UPDATE live_assist_queue_items SET status='played',updated_at=CURRENT_TIMESTAMP WHERE id=?",[current.id]);await this.record(itemDto(current),'played',input.actualDuration,input.startedAt);}const next=(await this.db.all("SELECT * FROM live_assist_queue_items WHERE queue_id=? AND position>? AND status='pending' ORDER BY position LIMIT 1",[queue.id,current?.position??-1]))[0];const stop=Boolean(queue.stop_after_current)||!queue.auto_advance||!next;await this.db.run('UPDATE live_assist_queues SET status=?,current_item_id=?,stop_after_current=0,updated_at=CURRENT_TIMESTAMP WHERE id=?',[stop?'stopped':'playing',stop?null:next.id,queue.id]);if(next&&!stop)await this.db.run("UPDATE live_assist_queue_items SET status='playing',updated_at=CURRENT_TIMESTAMP WHERE id=?",[next.id]);await this.recalculate(queue.id);return this.getQueue();}
  async configure(input={}){const queue=await this.queueRow();const status=input.status??queue.status;if(status==='stopped')await this.db.run("UPDATE live_assist_queue_items SET status='pending',updated_at=CURRENT_TIMESTAMP WHERE queue_id=? AND status='playing'",[queue.id]);await this.db.run('UPDATE live_assist_queues SET status=?,current_item_id=?,auto_advance=?,stop_after_current=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[status,status==='stopped'?null:queue.current_item_id,input.autoAdvance===undefined?queue.auto_advance:(input.autoAdvance?1:0),input.stopAfterCurrent===undefined?queue.stop_after_current:(input.stopAfterCurrent?1:0),queue.id]);return this.getQueue();}
  async clear(){const queue=await this.queueRow();await this.db.run('DELETE FROM live_assist_queue_items WHERE queue_id=?',[queue.id]);await this.db.run("UPDATE live_assist_queues SET status='stopped',current_item_id=NULL,stop_after_current=0,updated_at=CURRENT_TIMESTAMP WHERE id=?",[queue.id]);return this.getQueue();}
  async history(){return (await this.db.all('SELECT * FROM live_assist_history ORDER BY id DESC LIMIT 200')).map(r=>({id:r.id,queueItemId:r.queue_item_id,title:r.title,artist:r.artist,startedAt:r.started_at,endedAt:r.ended_at,actualDuration:r.actual_duration,result:r.result}));}
  async record(item,result,actualDuration=0,startedAt=null){await this.db.run('INSERT INTO live_assist_history (queue_item_id,title,artist,started_at,actual_duration,result) VALUES (?,?,?,?,?,?)',[item.id,item.title,item.artist,startedAt,Number(actualDuration||item.duration||0),result]);}
  async listPlaylists(){return (await this.db.all('SELECT * FROM saved_playlists ORDER BY updated_at DESC,id DESC')).map(playlistDto);}
  async getPlaylist(id){const row=(await this.db.all('SELECT * FROM saved_playlists WHERE id=?',[id]))[0];if(!row)throw new LiveAssistError('Playlist no encontrada.',404);return {...playlistDto(row),items:(await this.db.all('SELECT * FROM saved_playlist_items WHERE playlist_id=? ORDER BY position',[id])).map(r=>({id:r.id,playlistId:r.playlist_id,position:r.position,mediaId:r.media_id,cartwallButtonId:r.cartwall_button_id,type:r.item_type,title:r.title,artist:r.artist,duration:r.duration,metadata:parse(r.metadata_json)}))};}
  async createPlaylist(input){const queue=await this.getQueue();const name=String(input.name||'').trim();if(!name)throw new LiveAssistError('El nombre de la playlist es obligatorio.');if(!/^#[0-9a-f]{6}$/i.test(input.color||'#22d3ee'))throw new LiveAssistError('El color no es válido.');const result=await this.db.run('INSERT INTO saved_playlists (name,description,color,active,total_duration) VALUES (?,?,?,?,?)',[name,String(input.description||''),input.color||'#22d3ee',input.active===false?0:1,queue.items.reduce((s,i)=>s+i.duration,0)]);for(const [position,item] of queue.items.entries())await this.db.run('INSERT INTO saved_playlist_items (playlist_id,position,media_id,cartwall_button_id,item_type,title,artist,duration,metadata_json) VALUES (?,?,?,?,?,?,?,?,?)',[result.id,position,item.mediaId,item.cartwallButtonId,item.type,item.title,item.artist,item.duration,JSON.stringify(item.metadata)]);return this.getPlaylist(result.id);}
  async updatePlaylist(id,input){const current=await this.getPlaylist(id);const name=String(input.name??current.name).trim();if(!name)throw new LiveAssistError('El nombre es obligatorio.');const color=input.color??current.color;if(!/^#[0-9a-f]{6}$/i.test(color))throw new LiveAssistError('El color no es válido.');await this.db.run('UPDATE saved_playlists SET name=?,description=?,color=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[name,input.description??current.description,color,input.active===undefined?(current.active?1:0):(input.active?1:0),id]);return this.getPlaylist(id);}
  async deletePlaylist(id){await this.getPlaylist(id);await this.db.run('DELETE FROM saved_playlists WHERE id=?',[id]);return {deleted:true,id};}
  async duplicatePlaylist(id){const source=await this.getPlaylist(id);await this.loadPlaylist(id);return this.createPlaylist({name:`${source.name} (copia)`,description:source.description,color:source.color,active:false});}
  async loadPlaylist(id){const playlist=await this.getPlaylist(id);await this.clear();for(const item of playlist.items)await this.addItem({...item,status:'pending'});return this.getQueue();}
  async shift(queueId,from,delta){if(delta>0){const rows=await this.db.all('SELECT id,position FROM live_assist_queue_items WHERE queue_id=? AND position>=? ORDER BY position DESC',[queueId,from]);for(const row of rows)await this.db.run('UPDATE live_assist_queue_items SET position=? WHERE id=?',[row.position+delta,row.id]);}}
  async normalizePositions(queueId){const rows=await this.db.all('SELECT id FROM live_assist_queue_items WHERE queue_id=? ORDER BY position,id',[queueId]);await this.db.run('UPDATE live_assist_queue_items SET position=-(position+1) WHERE queue_id=?',[queueId]);for(const [position,row] of rows.entries())await this.db.run('UPDATE live_assist_queue_items SET position=? WHERE id=?',[position,row.id]);await this.recalculate(queueId);}
  async recalculate(queueId){const queue=(await this.db.all('SELECT * FROM live_assist_queues WHERE id=?',[queueId]))[0];const rows=await this.db.all('SELECT * FROM live_assist_queue_items WHERE queue_id=? ORDER BY position',[queueId]);let clock=Date.now();for(const row of rows){await this.db.run('UPDATE live_assist_queue_items SET scheduled_at=? WHERE id=?',[new Date(clock).toISOString(),row.id]);if(!['played','skipped'].includes(row.status))clock+=Number(row.duration||0)*1000;}if(queue.current_item_id&&!rows.some(r=>r.id===queue.current_item_id))await this.db.run("UPDATE live_assist_queues SET current_item_id=NULL,status='stopped' WHERE id=?",[queueId]);}
}
