export const musicalClockItemTypes = ['Canción', 'Categoría musical', 'Playlist', 'Jingle', 'Comercial', 'ID de emisora', 'Sweep', 'Locución DJ Virtual', 'Hora', 'Clima', 'Noticias', 'Evento', 'Espacio flexible'];
const HEX = /^#[0-9a-f]{6}$/i;

export class ClockError extends Error { constructor(message, status = 400, details = {}) { super(message); this.status = status; this.details = details; } }
export class ClockNotFoundError extends ClockError { constructor(label = 'Reloj musical') { super(`${label} no encontrado.`, 404); } }
export class ClockAssignedError extends ClockError { constructor(blocks) { super('El reloj está asignado a Programación.', 409); this.blocks = blocks; } }

const clockDto = row => ({ id: row.id, name: row.name, description: row.description, targetDuration: row.target_duration, color: row.color, active: Boolean(row.active), totalDuration: Number(row.total_duration || 0), itemCount: Number(row.item_count || 0), createdAt: row.created_at, updatedAt: row.updated_at });
const itemDto = row => ({ id: row.id, clockId: row.clock_id, position: row.position, name: row.name, type: row.type, estimatedDuration: row.estimated_duration, color: row.color, required: Boolean(row.required), skipIfUnavailable: Boolean(row.skip_if_unavailable), fadeIn: row.fade_in, fadeOut: row.fade_out, overlap: row.overlap, mediaId: row.media_id, playlistName: row.playlist_name, genre: row.genre, category: row.category, artistSeparationMinutes: row.artist_separation_minutes, trackSeparationMinutes: row.track_separation_minutes, songCount: row.song_count, voiceProfileId: row.voice_profile_id, scriptTemplate: row.script_template, metadata: safeJson(row.metadata_json), createdAt: row.created_at, updatedAt: row.updated_at });
const safeJson = value => { try { return JSON.parse(value || '{}'); } catch { return {}; } };

export class MusicalClockService {
  constructor(database) { this.db = database; }
  normalizeClock(input = {}, existing = {}) {
    const value = { name: String(input.name ?? existing.name ?? '').trim(), description: String(input.description ?? existing.description ?? '').trim(), targetDuration: Number(input.targetDuration ?? existing.targetDuration ?? 3600), color: String(input.color ?? existing.color ?? '#22d3ee'), active: input.active === undefined ? (existing.active ?? true) : Boolean(input.active) };
    const details = {}; if (!value.name) details.name = 'El nombre es obligatorio.'; if (!Number.isInteger(value.targetDuration) || value.targetDuration <= 0 || value.targetDuration > 86400) details.targetDuration = 'La duración objetivo debe ser válida.'; if (!HEX.test(value.color)) details.color = 'El color debe ser hexadecimal.'; if (Object.keys(details).length) throw new ClockError('Revisa los campos del reloj.', 400, details); return value;
  }
  normalizeItem(input = {}, existing = {}) {
    const number = (key, fallback = 0) => Number(input[key] ?? existing[key] ?? fallback);
    const value = { name: String(input.name ?? existing.name ?? '').trim(), type: String(input.type ?? existing.type ?? ''), estimatedDuration: number('estimatedDuration'), color: String(input.color ?? existing.color ?? '#22d3ee'), required: input.required === undefined ? (existing.required ?? true) : Boolean(input.required), skipIfUnavailable: input.skipIfUnavailable === undefined ? (existing.skipIfUnavailable ?? false) : Boolean(input.skipIfUnavailable), fadeIn: number('fadeIn'), fadeOut: number('fadeOut'), overlap: number('overlap'), mediaId: input.mediaId ?? existing.mediaId ?? null, playlistName: input.playlistName ?? existing.playlistName ?? null, genre: input.genre ?? existing.genre ?? null, category: input.category ?? existing.category ?? null, artistSeparationMinutes: number('artistSeparationMinutes'), trackSeparationMinutes: number('trackSeparationMinutes'), songCount: number('songCount', 1), voiceProfileId: input.voiceProfileId ?? existing.voiceProfileId ?? null, scriptTemplate: input.scriptTemplate ?? existing.scriptTemplate ?? null, metadata: input.metadata ?? existing.metadata ?? {} };
    const details = {}; if (!value.name) details.name = 'El nombre es obligatorio.'; if (!musicalClockItemTypes.includes(value.type)) details.type = 'El tipo no está permitido.'; for (const field of ['estimatedDuration','fadeIn','fadeOut','overlap','artistSeparationMinutes','trackSeparationMinutes']) if (!Number.isFinite(value[field]) || value[field] < 0) details[field] = 'El valor no puede ser negativo.'; if (!Number.isInteger(value.songCount) || value.songCount < 1) details.songCount = 'La cantidad debe ser al menos 1.'; if (!HEX.test(value.color)) details.color = 'El color debe ser hexadecimal.'; if (value.type === 'Canción' && !value.mediaId) details.mediaId = 'Selecciona una pista.'; if (value.type === 'Playlist' && !value.playlistName) details.playlistName = 'Selecciona una playlist.'; if (Object.keys(details).length) throw new ClockError('Revisa la posición.', 400, details); return value;
  }
  async list() { const rows = await this.db.all(`SELECT c.*, COUNT(i.id) item_count, COALESCE(SUM(i.estimated_duration - i.overlap),0) total_duration FROM musical_clocks c LEFT JOIN musical_clock_items i ON i.clock_id=c.id GROUP BY c.id ORDER BY c.updated_at DESC, c.name`); const clocks = rows.map(clockDto); for (const clock of clocks) clock.scheduleBlocks = await this.associations(clock.id); return clocks; }
  async get(id) { const rows = await this.db.all(`SELECT c.*, COUNT(i.id) item_count, COALESCE(SUM(i.estimated_duration - i.overlap),0) total_duration FROM musical_clocks c LEFT JOIN musical_clock_items i ON i.clock_id=c.id WHERE c.id=? GROUP BY c.id`, [id]); if (!rows[0]) throw new ClockNotFoundError(); return { ...clockDto(rows[0]), items: (await this.db.all('SELECT * FROM musical_clock_items WHERE clock_id=? ORDER BY position,id',[id])).map(itemDto), scheduleBlocks: await this.associations(id) }; }
  async associations(id) { return this.db.all('SELECT id,name,day_of_week AS dayOfWeek,start_time AS startTime,end_time AS endTime FROM schedule_blocks WHERE musical_clock_id=? ORDER BY day_of_week,start_time',[id]); }
  async create(input) { const v=this.normalizeClock(input); const result=await this.db.run('INSERT INTO musical_clocks (name,description,target_duration,color,active) VALUES (?,?,?,?,?)',[v.name,v.description,v.targetDuration,v.color,v.active?1:0]); return this.get(result.id); }
  async update(id,input) { const current=await this.get(id); const v=this.normalizeClock(input,current); await this.db.run('UPDATE musical_clocks SET name=?,description=?,target_duration=?,color=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[v.name,v.description,v.targetDuration,v.color,v.active?1:0,id]); return this.get(id); }
  async remove(id,force=false) { await this.get(id); const blocks=await this.associations(id); if(blocks.length&&!force) throw new ClockAssignedError(blocks); if(force&&blocks.length) await this.db.run('UPDATE schedule_blocks SET musical_clock_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE musical_clock_id=?',[id]); await this.db.run('DELETE FROM musical_clocks WHERE id=?',[id]); return {deleted:true,id,unassignedBlocks:blocks.length}; }
  async duplicate(id,input={}) { const source=await this.get(id); const copy=await this.create({name:input.name||`${source.name} (copia)`,description:source.description,targetDuration:source.targetDuration,color:source.color,active:input.active??false}); for(const item of source.items) await this.addItem(copy.id,{...item}); return this.get(copy.id); }
  async setStatus(id,active) { if(typeof active!=='boolean') throw new ClockError('El estado debe usar true o false.'); return this.update(id,{active}); }
  async addItem(clockId,input) { const clock=await this.get(clockId); const v=this.normalizeItem(input); const position=input.position===undefined?clock.items.length:Number(input.position); if(!Number.isInteger(position)||position<0||position>clock.items.length) throw new ClockError('La posición no es válida.'); await this.db.run('UPDATE musical_clock_items SET position=position+1 WHERE clock_id=? AND position>=?',[clockId,position]); const result=await this.db.run(`INSERT INTO musical_clock_items (clock_id,position,name,type,estimated_duration,color,required,skip_if_unavailable,fade_in,fade_out,overlap,media_id,playlist_name,genre,category,artist_separation_minutes,track_separation_minutes,song_count,voice_profile_id,script_template,metadata_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[clockId,position,v.name,v.type,v.estimatedDuration,v.color,v.required?1:0,v.skipIfUnavailable?1:0,v.fadeIn,v.fadeOut,v.overlap,v.mediaId,v.playlistName,v.genre,v.category,v.artistSeparationMinutes,v.trackSeparationMinutes,v.songCount,v.voiceProfileId,v.scriptTemplate,JSON.stringify(v.metadata)]); await this.touch(clockId); return (await this.db.all('SELECT * FROM musical_clock_items WHERE id=?',[result.id])).map(itemDto)[0]; }
  async getItem(clockId,itemId) { await this.get(clockId); const row=(await this.db.all('SELECT * FROM musical_clock_items WHERE id=? AND clock_id=?',[itemId,clockId]))[0]; if(!row) throw new ClockNotFoundError('Posición'); return itemDto(row); }
  async updateItem(clockId,itemId,input) { const current=await this.getItem(clockId,itemId); const v=this.normalizeItem(input,current); await this.db.run(`UPDATE musical_clock_items SET name=?,type=?,estimated_duration=?,color=?,required=?,skip_if_unavailable=?,fade_in=?,fade_out=?,overlap=?,media_id=?,playlist_name=?,genre=?,category=?,artist_separation_minutes=?,track_separation_minutes=?,song_count=?,voice_profile_id=?,script_template=?,metadata_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND clock_id=?`,[v.name,v.type,v.estimatedDuration,v.color,v.required?1:0,v.skipIfUnavailable?1:0,v.fadeIn,v.fadeOut,v.overlap,v.mediaId,v.playlistName,v.genre,v.category,v.artistSeparationMinutes,v.trackSeparationMinutes,v.songCount,v.voiceProfileId,v.scriptTemplate,JSON.stringify(v.metadata),itemId,clockId]); await this.touch(clockId); return this.getItem(clockId,itemId); }
  async removeItem(clockId,itemId) { const item=await this.getItem(clockId,itemId); await this.db.run('DELETE FROM musical_clock_items WHERE id=?',[itemId]); await this.db.run('UPDATE musical_clock_items SET position=position-1 WHERE clock_id=? AND position>?',[clockId,item.position]); await this.touch(clockId); return {deleted:true,id:itemId}; }
  async duplicateItem(clockId,itemId) { const source=await this.getItem(clockId,itemId); return this.addItem(clockId,{...source,name:`${source.name} (copia)`,position:source.position+1}); }
  async reorder(clockId,itemIds) { const clock=await this.get(clockId); if(!Array.isArray(itemIds)||itemIds.length!==clock.items.length||new Set(itemIds).size!==itemIds.length||!clock.items.every(item=>itemIds.includes(item.id))) throw new ClockError('El orden debe incluir todas las posiciones una sola vez.'); for(const [position,id] of itemIds.entries()) await this.db.run('UPDATE musical_clock_items SET position=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND clock_id=?',[position,id,clockId]); await this.touch(clockId); return (await this.get(clockId)).items; }
  async touch(id) { await this.db.run('UPDATE musical_clocks SET updated_at=CURRENT_TIMESTAMP WHERE id=?',[id]); }
}
