import { spawn } from 'node:child_process';
import { createReadStream, createWriteStream } from 'node:fs';
import { createServer } from 'node:http';
import { mkdir, readdir, rename, rm, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { Readable, Transform } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { randomUUID } from 'node:crypto';

const json=value=>{try{return JSON.parse(value||'{}')}catch{return {}}};
const bool=value=>Boolean(Number(value));
const runProcess=(binary,args,{timeoutMs=120000,onSpawn}={})=>new Promise((resolve,reject)=>{
  const child=spawn(binary,args,{windowsHide:true,stdio:['ignore','pipe','pipe']});onSpawn?.(child);
  let stdout='',stderr='';child.stdout.on('data',chunk=>stdout+=chunk);child.stderr.on('data',chunk=>stderr+=chunk);
  const timer=setTimeout(()=>{child.kill('SIGKILL');reject(new Error(`${binary} excedió el tiempo permitido.`))},timeoutMs);
  child.once('error',error=>{clearTimeout(timer);reject(error)});child.once('close',code=>{clearTimeout(timer);code===0?resolve({stdout,stderr}):reject(new Error(`${binary} terminó con código ${code}: ${stderr.slice(-600)}`))});
});

export class OnAirError extends Error{constructor(message,status=400){super(message);this.status=status}}
export class AudioAdapter{constructor(name){this.name=name}async detect(){return {available:false,name:this.name,version:null}}async render(){throw new OnAirError('El adaptador no puede generar audio.',503)}stop(){}}
export class SilentDiagnosticAdapter extends AudioAdapter{constructor(){super('diagnostic')}async detect(){return {available:true,name:this.name,version:'Diagnóstico silencioso'}}}
export class FfmpegAudioAdapter extends AudioAdapter{
  constructor({ffmpeg=process.env.FFMPEG_PATH||'ffmpeg',ffprobe=process.env.FFPROBE_PATH||'ffprobe'}={}){super('ffmpeg');this.ffmpeg=ffmpeg;this.ffprobe=ffprobe;this.child=null;}
  async detect(){try{const result=await runProcess(this.ffmpeg,['-version'],{timeoutMs:5000});return {available:true,name:this.name,version:result.stdout.split(/\r?\n/)[0]}}catch{return {available:false,name:this.name,version:null}}}
  async render({inputs,output,codec='mp3',bitrate=128,sampleRate=44100,channels=2,fadeIn=0,fadeOut=0,crossfade=0,gainDb=0}){
    if(!inputs.length)throw new OnAirError('No hay pistas para procesar.',409);
    const args=['-hide_banner','-y'];inputs.forEach(input=>args.push('-i',input.path));
    const chains=[];inputs.forEach((input,index)=>{let filters=`aformat=sample_rates=${sampleRate}:channel_layouts=${channels===1?'mono':'stereo'}`;if(fadeIn>0)filters+=`,afade=t=in:st=0:d=${fadeIn}`;if(fadeOut>0&&input.duration>fadeOut)filters+=`,afade=t=out:st=${Math.max(0,input.duration-fadeOut)}:d=${fadeOut}`;chains.push(`[${index}:a]${filters}[a${index}]`)});
    let label='a0';if(inputs.length>1){if(crossfade>0){for(let index=1;index<inputs.length;index+=1){const out=`mix${index}`;chains.push(`[${label}][a${index}]acrossfade=d=${crossfade}:c1=tri:c2=tri[${out}]`);label=out}}else{chains.push(`${inputs.map((_,index)=>`[a${index}]`).join('')}concat=n=${inputs.length}:v=0:a=1[mix]`);label='mix'}}
    chains.push(`[${label}]volume=${gainDb}dB[out]`);args.push('-filter_complex',chains.join(';'),'-map','[out]','-ar',String(sampleRate),'-ac',String(channels));
    if(codec==='mp3')args.push('-c:a','libmp3lame','-b:a',`${bitrate}k`);else if(codec==='aac')args.push('-c:a','aac','-b:a',`${bitrate}k`);else if(codec==='ogg')args.push('-c:a','libvorbis','-b:a',`${bitrate}k`);else if(codec==='flac')args.push('-c:a','flac');else args.push('-c:a','pcm_s16le');
    args.push(output);await runProcess(this.ffmpeg,args,{timeoutMs:300000,onSpawn:child=>{this.child=child}});this.child=null;return this.probe(output);
  }
  async probe(file){const result=await runProcess(this.ffprobe,['-v','error','-show_entries','format=duration,size,bit_rate:stream=codec_name,sample_rate,channels','-of','json',file],{timeoutMs:15000});const data=JSON.parse(result.stdout);const stream=data.streams?.[0]||{};return {path:file,duration:Number(data.format?.duration||0),size:Number(data.format?.size||0),bitrate:Number(data.format?.bit_rate||0),codec:stream.codec_name||null,sampleRate:Number(stream.sample_rate||0),channels:Number(stream.channels||0)}}
  stop(){if(this.child&&!this.child.killed)this.child.kill('SIGKILL');this.child=null;}
}

export class ProgressiveMediaCache{
  constructor({mediaProvider,cacheDir=process.env.ON_AIR_MEDIA_CACHE_DIR||path.join(tmpdir(),'ptr-on-air-cache'),idleTimeoutMs=Number(process.env.ON_AIR_MEDIA_IDLE_TIMEOUT_MS||30000),maxDownloadMs=Number(process.env.ON_AIR_MEDIA_MAX_DOWNLOAD_MS||0),maxMb=Number(process.env.ON_AIR_MEDIA_CACHE_MAX_MB||2048),ttlHours=Number(process.env.ON_AIR_MEDIA_CACHE_TTL_HOURS||24)}={}){this.mediaProvider=mediaProvider;this.cacheDir=cacheDir;this.idleTimeoutMs=Math.max(10,idleTimeoutMs);this.maxDownloadMs=Math.max(0,maxDownloadMs);this.maxBytes=Math.max(.001,maxMb)*1024*1024;this.ttlMs=Math.max(.001,ttlHours)*3600000;this.inflight=new Map();this.controllers=new Set();}
  key(mediaId){return Buffer.from(String(mediaId)).toString('base64url').slice(0,180)}
  async initialize(){await mkdir(this.cacheDir,{recursive:true});await this.cleanup()}
  async get(item){await mkdir(this.cacheDir,{recursive:true});const key=this.key(item.media_id),file=path.join(this.cacheDir,`${key}.media`);try{const info=await stat(file);if(Date.now()-info.mtimeMs<this.ttlMs)return {path:file,duration:Number(item.duration||0),title:item.title,cached:true,size:info.size}}catch{}if(this.inflight.has(key))return this.inflight.get(key);const promise=this.download(item,file).finally(()=>this.inflight.delete(key));this.inflight.set(key,promise);return promise}
  async download(item,file){let lastError;for(let attempt=1;attempt<=2;attempt+=1){const part=`${file}.part-${randomUUID()}`,controller=new AbortController();this.controllers.add(controller);let idleTimer,totalTimer,guard,bytes=0;const resetIdle=()=>{clearTimeout(idleTimer);idleTimer=setTimeout(()=>{const error=new OnAirError(`Transferencia inactiva durante ${this.idleTimeoutMs} ms: ${item.title}.`,504);controller.abort(error);guard?.destroy(error)},this.idleTimeoutMs)};try{const response=await this.mediaProvider(item.media_id,null,controller.signal);if(!response.ok)throw new OnAirError(`No se pudo abrir ${item.title}.`,502);const length=Number(response.headers.get('content-length')||0);if(length>this.maxBytes)throw new OnAirError(`El archivo excede el máximo de caché (${Math.round(this.maxBytes/1024/1024)} MB).`,413);guard=new Transform({transform:(chunk,_encoding,callback)=>{bytes+=chunk.length;resetIdle();callback(null,chunk)}});resetIdle();if(this.maxDownloadMs>0)totalTimer=setTimeout(()=>{const error=new OnAirError(`La transferencia excedió ${this.maxDownloadMs} ms.`,504);controller.abort(error);guard.destroy(error)},this.maxDownloadMs);await pipeline(Readable.fromWeb(response.body),guard,createWriteStream(part));clearTimeout(idleTimer);clearTimeout(totalTimer);await rename(part,file);await this.cleanup();return {path:file,duration:Number(item.duration||0),title:item.title,cached:false,size:bytes}}catch(error){lastError=controller.signal.reason instanceof Error?controller.signal.reason:error;await rm(part,{force:true});if(controller.signal.aborted&&String(lastError?.message).includes('inactiva'))break}finally{clearTimeout(idleTimer);clearTimeout(totalTimer);this.controllers.delete(controller)}}throw lastError}
  async cleanup(){await mkdir(this.cacheDir,{recursive:true});const entries=[];for(const name of await readdir(this.cacheDir)){const file=path.join(this.cacheDir,name);try{const info=await stat(file);if(name.includes('.part-')||Date.now()-info.mtimeMs>this.ttlMs)await rm(file,{force:true});else entries.push({file,size:info.size,mtime:info.mtimeMs})}catch{}}entries.sort((a,b)=>a.mtime-b.mtime);let total=entries.reduce((sum,item)=>sum+item.size,0);for(const item of entries){if(total<=this.maxBytes)break;await rm(item.file,{force:true});total-=item.size}return {files:entries.length,totalBytes:Math.max(0,total)}}
  cancel(){for(const controller of this.controllers)controller.abort(new Error('Transferencia inactiva cancelada por el operador.'));this.controllers.clear()}
}

export class OnAirEngineService{
  constructor(db,{mediaProvider,ffmpegAdapter=new FfmpegAudioAdapter(),diagnosticAdapter=new SilentDiagnosticAdapter(),mediaCache,now=()=>new Date()}={}){this.db=db;this.mediaProvider=mediaProvider;this.ffmpeg=ffmpegAdapter;this.diagnostic=diagnosticAdapter;this.cache=mediaCache||new ProgressiveMediaCache({mediaProvider});this.now=now;this.owner=randomUUID();this.process=null;this.streamServer=null;this.streamClients=new Set();this.streamStartedAt=null;this.heartbeat=null;this.metrics={left:null,right:null,peak:null,rms:null,signal:'No disponible',bytesProcessed:0,connectedSeconds:0,reconnections:0};}
  async initialize(){const detection=await this.ffmpeg.detect();await this.cache.initialize();await this.db.run("UPDATE on_air_config SET adapter=?,status='standby',process_owner=NULL,last_heartbeat_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=1",[detection.available?'ffmpeg':'diagnostic']);this.detection=detection;this.startHeartbeat();return this.status()}
  startHeartbeat(){if(this.heartbeat)return;this.heartbeat=setInterval(()=>this.db.run('UPDATE on_air_config SET last_heartbeat_at=CURRENT_TIMESTAMP WHERE id=1').catch(()=>{}),1000);this.heartbeat.unref?.()}
  async configRow(){return (await this.db.all('SELECT * FROM on_air_config WHERE id=1'))[0]}
  outputDto=row=>({...row,enabled:bool(row.enabled),testOnly:bool(row.test_only),active:bool(row.active),passwordEnvKey:row.password_env_key,hasPassword:Boolean(row.password_env_key&&process.env[row.password_env_key]),password_env_key:undefined})
  async outputs(){return (await this.db.all('SELECT * FROM on_air_outputs ORDER BY id')).map(row=>this.outputDto(row))}
  async status(){const config=await this.configRow(),session=(await this.db.all('SELECT * FROM on_air_sessions ORDER BY id DESC LIMIT 1'))[0]||null,outputs=await this.outputs();return {mode:'test-only',status:config.status,adapter:config.adapter,detection:this.detection||await this.ffmpeg.detect(),sourceType:config.source_type,current:config.current_title,next:config.next_title,output:outputs.find(item=>item.id===config.output_id)||outputs[0]||null,session,heartbeat:config.last_heartbeat_at,watchdogEnabled:bool(config.watchdog_enabled),silenceDetector:{enabled:false,timeoutSeconds:config.silence_timeout_seconds},localStream:this.streamServer?{online:true,url:`http://127.0.0.1:${Number(process.env.ON_AIR_LOCAL_STREAM_PORT||8092)}/stream.mp3`,clients:this.streamClients.size}:null,metrics:{...this.metrics,connectedSeconds:this.streamStartedAt?Math.floor((Date.now()-this.streamStartedAt)/1000):0,bytesProcessed:Number(this.streamServer?this.metrics.bytesProcessed:(session?.bytes_sent||this.metrics.bytesProcessed))},protectionActive:true,principalConnected:false,autoDjControlled:false}}
  async config(){const row=await this.configRow();return {fadeInSeconds:row.fade_in_seconds,fadeOutSeconds:row.fade_out_seconds,crossfadeSeconds:row.crossfade_seconds,cueInSeconds:row.cue_in_seconds,cueOutSeconds:row.cue_out_seconds,trimSilence:bool(row.trim_silence),masterGainDb:row.master_gain_db,normalization:row.normalization,volumes:{master:row.master_volume,music:row.music_volume,jingle:row.jingle_volume,commercial:row.commercial_volume,cartwall:row.cartwall_volume,voiceTrack:row.voice_track_volume,emergency:row.emergency_volume},silenceTimeoutSeconds:row.silence_timeout_seconds,watchdogEnabled:bool(row.watchdog_enabled),liveLocked:true}}
  async events(limit=100){return (await this.db.all('SELECT * FROM on_air_events ORDER BY id DESC LIMIT ?',[Math.min(500,Number(limit)||100)])).map(row=>({id:row.id,sessionId:row.session_id,type:row.event_type,message:row.message,metadata:json(row.metadata_json),createdAt:row.created_at}))}
  async event(type,message,metadata={}){const session=(await this.db.all('SELECT id FROM on_air_sessions ORDER BY id DESC LIMIT 1'))[0];await this.db.run('INSERT INTO on_air_events (session_id,event_type,message,metadata_json) VALUES (?,?,?,?)',[session?.id||null,type,message,JSON.stringify(metadata)])}
  async sourceItems(type='live-assist'){if(type==='live-assist'){const queue=(await this.db.all('SELECT id FROM live_assist_queues ORDER BY id LIMIT 1'))[0];return queue?this.db.all("SELECT media_id,title,artist,duration FROM live_assist_queue_items WHERE queue_id=? AND media_id IS NOT NULL ORDER BY position LIMIT 3",[queue.id]):[]}if(type==='automation')return this.db.all("SELECT media_id,title,artist,duration FROM automation_queue_items WHERE media_id IS NOT NULL ORDER BY id DESC LIMIT 3");throw new OnAirError('La prueba v1 admite Live Assist o Automatización.',422)}
  async download(item){return this.cache.get(item)}
  async startFileTest({sourceType='live-assist',confirmOutput=false,confirmStart=false}={}){if(!confirmOutput||!confirmStart)throw new OnAirError('Se requieren las dos confirmaciones de salida de prueba.',409);if(this.process)throw new OnAirError('Ya existe una salida de prueba activa.',409);const output=(await this.db.all("SELECT * FROM on_air_outputs WHERE output_type='file' AND enabled=1 AND test_only=1 ORDER BY id LIMIT 1"))[0];if(!output)throw new OnAirError('Habilita primero la salida local de prueba.',409);if(!this.detection?.available)throw new OnAirError('FFmpeg no está instalado; continúa disponible el diagnóstico silencioso.',503);const items=await this.sourceItems(sourceType);if(items.length<3)throw new OnAirError('La prueba necesita al menos tres pistas con media_id.',409);const config=await this.configRow(),directory=path.join(tmpdir(),`ptr-on-air-${randomUUID()}`),target=process.env.ON_AIR_TEST_FILE||path.join(tmpdir(),'ptr-on-air-test.mp3');await mkdir(directory,{recursive:true});const session=await this.db.run("INSERT INTO on_air_sessions (output_id,status) VALUES (?,'starting')",[output.id]);this.process={sessionId:session.id,directory};await this.db.run("UPDATE on_air_config SET status='starting',output_id=?,source_type=?,current_title=?,next_title=?,process_owner=?,last_error=NULL WHERE id=1",[output.id,sourceType,items[0].title,items[1].title,this.owner]);await this.event('starting','Iniciando archivo de prueba local protegido.');try{const inputs=[];for(const item of items)inputs.push(await this.download(item));await this.db.run("UPDATE on_air_config SET status='rendering' WHERE id=1");const result=await this.ffmpeg.render({inputs,output:target,codec:output.codec,bitrate:output.bitrate,sampleRate:output.sample_rate,channels:output.channels,fadeIn:config.fade_in_seconds,fadeOut:config.fade_out_seconds,crossfade:config.crossfade_seconds,gainDb:config.master_gain_db});await this.db.run("UPDATE on_air_sessions SET status='completed',ended_at=CURRENT_TIMESTAMP,bytes_sent=?,stop_reason='file_complete' WHERE id=?",[result.size,session.id]);await this.db.run("UPDATE on_air_config SET status='completed',current_title=NULL,next_title=NULL,process_owner=NULL WHERE id=1");this.metrics.bytesProcessed=result.size;await this.event('file_complete','Archivo local de prueba generado.',result);return {...await this.status(),file:result}}catch(error){await this.db.run("UPDATE on_air_sessions SET status='error',ended_at=CURRENT_TIMESTAMP,stop_reason='render_error' WHERE id=?",[session.id]);await this.db.run("UPDATE on_air_config SET status='error',last_error=?,process_owner=NULL WHERE id=1",[error.message]);await this.event('error',error.message);throw error}finally{this.process=null;await rm(directory,{recursive:true,force:true})}}
  async startLocalStream({confirmOutput=false,confirmStart=false}={}){if(!confirmOutput||!confirmStart)throw new OnAirError('Se requieren las dos confirmaciones para el stream local.',409);if(this.streamServer)throw new OnAirError('La salida local ya está activa.',409);const file=process.env.ON_AIR_TEST_FILE||path.join(tmpdir(),'ptr-on-air-test.mp3');try{await stat(file)}catch{throw new OnAirError('Genera primero el archivo local de prueba.',409)}const port=Number(process.env.ON_AIR_LOCAL_STREAM_PORT||8092),bytesPerSecond=128000/8;this.streamServer=createServer((req,res)=>{if(req.url!=='/stream.mp3'){res.writeHead(404,{'Content-Type':'text/plain'});return res.end('Not found')}res.writeHead(200,{'Content-Type':'audio/mpeg','Cache-Control':'no-store','Connection':'keep-alive'});this.streamClients.add(res);let activeInput,resumeTimer;const loop=()=>{if(res.destroyed)return;activeInput=createReadStream(file,{highWaterMark:16384});activeInput.on('data',chunk=>{activeInput.pause();this.metrics.bytesProcessed+=chunk.length;res.write(chunk);resumeTimer=setTimeout(()=>activeInput?.resume(),Math.max(1,Math.round(chunk.length/bytesPerSecond*1000)))});activeInput.once('error',()=>{if(!res.destroyed)res.destroy()});activeInput.once('end',loop)};res.once('close',()=>{clearTimeout(resumeTimer);activeInput?.destroy();this.streamClients.delete(res)});loop()});await new Promise((resolve,reject)=>{this.streamServer.once('error',reject);this.streamServer.listen(port,'127.0.0.1',resolve)});this.streamStartedAt=Date.now();this.metrics.signal='Activa';this.metrics.bytesProcessed=0;await this.db.run("UPDATE on_air_config SET status='streaming_local',process_owner=?,last_error=NULL WHERE id=1",[this.owner]);await this.event('local_stream_started',`Stream local iniciado en 127.0.0.1:${port}.`);return this.status()}
  async stopLocalStream(){for(const client of this.streamClients)client.destroy();this.streamClients.clear();if(this.streamServer)await new Promise(resolve=>this.streamServer.close(resolve));this.streamServer=null;this.streamStartedAt=null;this.metrics.signal='No disponible'}
  async stop(reason='operator_stop'){this.cache.cancel();this.ffmpeg.stop();await this.stopLocalStream();if(this.process?.directory)await rm(this.process.directory,{recursive:true,force:true});this.process=null;await this.db.run("UPDATE on_air_sessions SET status='stopped',ended_at=CURRENT_TIMESTAMP,stop_reason=? WHERE status IN ('starting','rendering')",[reason]);await this.db.run("UPDATE on_air_config SET status='standby',current_title=NULL,next_title=NULL,process_owner=NULL WHERE id=1");await this.event(reason==='emergency_stop'?'emergency_stop':'stopped',`Salida de prueba detenida: ${reason}.`);return this.status()}
  async updateOutput(id,input={}){const current=(await this.db.all('SELECT * FROM on_air_outputs WHERE id=?',[id]))[0];if(!current)throw new OnAirError('Salida no encontrada.',404);if(input.testOnly===false)throw new OnAirError('Solo se permiten salidas test_only en v1.',403);const enabled=input.enabled===undefined?current.enabled:(input.enabled?1:0);await this.db.run('UPDATE on_air_outputs SET enabled=?,test_only=1,updated_at=CURRENT_TIMESTAMP WHERE id=?',[enabled,id]);return (await this.outputs()).find(item=>item.id===Number(id))}
  async updateConfig(input={}){const current=await this.configRow(),number=(value,fallback,min,max)=>{const result=Number(value??fallback);if(!Number.isFinite(result)||result<min||result>max)throw new OnAirError(`Valor fuera del rango ${min}-${max}.`);return result};await this.db.run(`UPDATE on_air_config SET fade_in_seconds=?,fade_out_seconds=?,crossfade_seconds=?,cue_in_seconds=?,master_gain_db=?,silence_timeout_seconds=?,watchdog_enabled=?,updated_at=CURRENT_TIMESTAMP WHERE id=1`,[number(input.fadeInSeconds,current.fade_in_seconds,0,30),number(input.fadeOutSeconds,current.fade_out_seconds,0,30),number(input.crossfadeSeconds,current.crossfade_seconds,0,15),number(input.cueInSeconds,current.cue_in_seconds,0,3600),number(input.masterGainDb,current.master_gain_db,-24,12),number(input.silenceTimeoutSeconds,current.silence_timeout_seconds,5,600),input.watchdogEnabled===undefined?current.watchdog_enabled:(input.watchdogEnabled?1:0)]);return this.config()}
  async updateVolumes(input={}){const current=await this.configRow(),keys=['master','music','jingle','commercial','cartwall','voiceTrack','emergency'],columns=['master_volume','music_volume','jingle_volume','commercial_volume','cartwall_volume','voice_track_volume','emergency_volume'],values=keys.map((key,index)=>{const value=Number(input[key]??current[columns[index]]);if(!Number.isFinite(value)||value<0||value>1)throw new OnAirError('Los volúmenes deben estar entre 0 y 1.');return value});await this.db.run(`UPDATE on_air_config SET ${columns.map(column=>`${column}=?`).join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=1`,values);return this.config()}
  async metricsStatus(){return (await this.status()).metrics}
  async recover(){await this.stop('recovery');return this.initialize()}
  shutdown(){this.cache.cancel();this.ffmpeg.stop();for(const client of this.streamClients)client.destroy();this.streamServer?.close();if(this.heartbeat)clearInterval(this.heartbeat);this.heartbeat=null}
}
