import { randomUUID } from 'node:crypto';

const activeStatuses=new Set(['starting','playing','paused','recovering']);
const json=value=>{try{return JSON.parse(value||'{}')}catch{return {}}};
export class ServerAudioError extends Error{constructor(message,status=400){super(message);this.status=status;}}
export class DiagnosticAudioAdapter{
  constructor({mediaProvider}){this.mediaProvider=mediaProvider;}
  async probe(mediaId){if(!mediaId)throw new ServerAudioError('El elemento no contiene media_id.',422);const response=await this.mediaProvider(mediaId,'bytes=0-65535');const type=(response.headers.get('content-type')||'').toLowerCase();const reader=response.body?.getReader();const chunk=reader?await reader.read():{value:new Uint8Array()};await reader?.cancel();const bytes=chunk.value||new Uint8Array();const text=String.fromCharCode(...bytes.slice(0,12));let format=type.includes('flac')||text.startsWith('fLaC')?'flac':type.includes('mpeg')||text.startsWith('ID3')||bytes[0]===0xff?'mp3':type.includes('aac')?'aac':type.includes('wav')||text.includes('WAVE')?'wav':type.includes('ogg')||text.startsWith('OggS')?'ogg':null;if(!format)throw new ServerAudioError(`Formato de audio no compatible (${type||'desconocido'}).`,422);return {format,contentType:type,bytesInspected:bytes.length};}
}
const stateDto=row=>({id:row.id,mode:row.mode,status:row.status,activeSource:row.active_source,activeQueueId:row.active_queue_id,currentItemId:row.current_item_id,currentStartedAt:row.current_started_at,currentPositionSeconds:Number(row.current_position_seconds||0),masterVolume:Number(row.master_volume),crossfadeSeconds:Number(row.crossfade_seconds),autoRecovery:Boolean(row.auto_recovery),watchdogEnabled:Boolean(row.watchdog_enabled),silenceTimeoutSeconds:row.silence_timeout_seconds,lastHeartbeatAt:row.last_heartbeat_at,errorMessage:row.error_message});
const itemDto=row=>row?({id:row.id,sessionId:row.session_id,position:row.position,sourceItemId:row.source_item_id,mediaId:row.media_id,title:row.title,artist:row.artist,duration:Number(row.duration||0),status:row.status,format:row.format,metadata:json(row.metadata_json)}):null;

export class ServerAudioEngineService{
  constructor(db,{adapter,intervalMs=1000,now=()=>new Date()}={}){this.db=db;this.adapter=adapter;this.intervalMs=intervalMs;this.now=now;this.owner=randomUUID();this.timer=null;this.opening=false;this.lastSchedulerKey='';}
  async initialize(){const state=await this.row();if(activeStatuses.has(state.status)){const message='Se detectó una sesión interrumpida; no se duplicó el reproductor.';if(state.auto_recovery)await this.recover(message);else{await this.db.run("UPDATE server_audio_engine SET status='recovering',mode='test',process_owner=?,error_message='Proceso reiniciado; recuperación segura requerida.',updated_at=CURRENT_TIMESTAMP WHERE id=1",[this.owner]);await this.event('recovering',message);}}this.startLoop();return this.status();}
  startLoop(){if(this.timer)return;this.timer=setInterval(()=>this.tick().catch(error=>this.fail(error)),this.intervalMs);this.timer.unref?.();}
  stopLoop(){if(this.timer)clearInterval(this.timer);this.timer=null;}
  async row(){return (await this.db.all('SELECT * FROM server_audio_engine WHERE id=1'))[0];}
  async status(){const state=await this.row();const session=state.active_queue_id?(await this.db.all('SELECT * FROM server_audio_sessions WHERE id=?',[state.active_queue_id]))[0]:null;const items=session?(await this.db.all('SELECT * FROM server_audio_queue_items WHERE session_id=? ORDER BY position',[session.id])).map(itemDto):[];const current=items.find(i=>i.id===state.current_item_id)||null;const next=items.find(i=>i.position>(current?.position??-1)&&i.status==='pending')||null;return {...stateDto(state),session:session?{id:session.id,sourceType:session.source_type,sourceId:session.source_id,mode:session.mode,status:session.status,startedAt:session.started_at}:null,current,next,queue:items,outputProtected:true,output:'Diagnóstico silencioso',liveEnabled:false};}
  async current(){const status=await this.status();return {current:status.current,next:status.next,elapsed:status.currentPositionSeconds,remaining:Math.max(0,(status.current?.duration||0)-status.currentPositionSeconds),serverTime:this.now().toISOString()};}
  async events(limit=100){return (await this.db.all('SELECT * FROM server_audio_events ORDER BY id DESC LIMIT ?',[Math.min(500,Number(limit)||100)])).map(row=>({id:row.id,sessionId:row.session_id,queueItemId:row.queue_item_id,type:row.event_type,message:row.message,metadata:json(row.metadata_json),createdAt:row.created_at}));}
  async config(){const state=await this.row();const outputs=await this.db.all('SELECT id,name,output_type AS outputType,host,port,mount,username,enabled,test_only AS testOnly,created_at AS createdAt,updated_at AS updatedAt FROM server_audio_outputs');return {...stateDto(state),outputs:outputs.map(o=>({...o,enabled:Boolean(o.enabled),testOnly:Boolean(o.testOnly),hasPasswordReference:false}))};}
  async sourceItems(type,id){if(type==='live-assist'){const queue=(await this.db.all('SELECT id FROM live_assist_queues ORDER BY id LIMIT 1'))[0];return queue?this.db.all("SELECT id,position,media_id,title,artist,duration,metadata_json FROM live_assist_queue_items WHERE queue_id=? AND status IN ('pending','playing') ORDER BY position",[queue.id]):[];}if(type==='automation'){const run=id?(await this.db.all('SELECT id FROM automation_runs WHERE id=?',[id]))[0]:(await this.db.all('SELECT id FROM automation_runs ORDER BY id DESC LIMIT 1'))[0];return run?this.db.all("SELECT id,position,media_id,title,artist,duration,metadata_json FROM automation_queue_items WHERE run_id=? AND status IN ('ready','pending','playing') ORDER BY position",[run.id]):[];}if(type==='playlist'){return this.db.all('SELECT id,position,media_id,title,artist,duration,metadata_json FROM saved_playlist_items WHERE playlist_id=? ORDER BY position',[id]);}throw new ServerAudioError('Fuente no compatible. Usa live-assist, automation o playlist.');}
  async start({sourceType='live-assist',sourceId=null,mode='test'}={}){if(!['test','preview'].includes(mode))throw new ServerAudioError('El modo live está bloqueado en v1.',403);const state=await this.row();if(activeStatuses.has(state.status)&&state.process_owner&&state.process_owner!==this.owner)throw new ServerAudioError('Ya existe otro motor activo.',409);if(activeStatuses.has(state.status))throw new ServerAudioError('El motor ya está activo.',409);const source=await this.sourceItems(sourceType,sourceId);if(!source.length)throw new ServerAudioError('La fuente seleccionada no contiene elementos reproducibles.',409);const session=await this.db.run('INSERT INTO server_audio_sessions (source_type,source_id,mode,status) VALUES (?,?,?,?)',[sourceType,sourceId,mode,'starting']);for(const [position,item] of source.entries())await this.db.run('INSERT INTO server_audio_queue_items (session_id,position,source_item_id,media_id,title,artist,duration,status,metadata_json) VALUES (?,?,?,?,?,?,?,?,?)',[session.id,position,item.id,item.media_id,item.title,item.artist||'',Number(item.duration||0),'pending',item.metadata_json||'{}']);const first=(await this.db.all('SELECT id FROM server_audio_queue_items WHERE session_id=? ORDER BY position LIMIT 1',[session.id]))[0];await this.db.run("UPDATE server_audio_engine SET mode=?,status='starting',active_source=?,active_queue_id=?,current_item_id=?,current_position_seconds=0,current_started_at=NULL,error_message=NULL,process_owner=?,updated_at=CURRENT_TIMESTAMP WHERE id=1",[mode,sourceType,session.id,first.id,this.owner]);await this.event('session_started',`Sesión ${mode} iniciada desde ${sourceType}.`,{sessionId:session.id});this.startLoop();await this.openCurrent();return this.status();}
  async openCurrent(){if(this.opening)return;this.opening=true;let failure=null;try{const state=await this.row();const item=(await this.db.all('SELECT * FROM server_audio_queue_items WHERE id=?',[state.current_item_id]))[0];if(!item)return this.finish('queue_complete');await this.db.run("UPDATE server_audio_queue_items SET status='preloading',updated_at=CURRENT_TIMESTAMP WHERE id=?",[item.id]);const probe=await this.adapter.probe(item.media_id);await this.db.run("UPDATE server_audio_queue_items SET status='playing',format=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",[probe.format,item.id]);await this.db.run("UPDATE server_audio_engine SET status='playing',current_started_at=CURRENT_TIMESTAMP,last_heartbeat_at=CURRENT_TIMESTAMP,error_message=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=1");await this.db.run("UPDATE server_audio_sessions SET status='playing',updated_at=CURRENT_TIMESTAMP WHERE id=?",[state.active_queue_id]);await this.event('playing',`${item.title} validado y reproduciendo en salida silenciosa.`,{queueItemId:item.id,...probe});}catch(error){failure=error}finally{this.opening=false}if(failure)await this.handleItemError(failure);}
  async tick(){const state=await this.row();await this.db.run('UPDATE server_audio_engine SET last_heartbeat_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=1');await this.schedulerCheck();if(state.status!=='playing')return;const item=(await this.db.all('SELECT * FROM server_audio_queue_items WHERE id=?',[state.current_item_id]))[0];if(!item)return this.recover('Elemento actual ausente.');const nextPosition=Number(state.current_position_seconds||0)+this.intervalMs/1000;if(nextPosition>=Number(item.duration||0))return this.advance('completed');await this.db.run('UPDATE server_audio_engine SET current_position_seconds=? WHERE id=1',[nextPosition]);}
  async advance(result='completed'){const state=await this.row();const item=(await this.db.all('SELECT * FROM server_audio_queue_items WHERE id=?',[state.current_item_id]))[0];if(item){await this.db.run('UPDATE server_audio_queue_items SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[result==='completed'?'played':result,item.id]);await this.event(result,`${item.title}: ${result}.`,{queueItemId:item.id});}const next=(await this.db.all("SELECT id FROM server_audio_queue_items WHERE session_id=? AND position>? AND status='pending' ORDER BY position LIMIT 1",[state.active_queue_id,item?.position??-1]))[0];if(!next)return this.finish('queue_complete');await this.db.run("UPDATE server_audio_engine SET current_item_id=?,current_position_seconds=0,current_started_at=NULL,status='starting',updated_at=CURRENT_TIMESTAMP WHERE id=1",[next.id]);await this.openCurrent();return this.status();}
  async pause(){const state=await this.row();if(state.status!=='playing')throw new ServerAudioError('El motor no está reproduciendo.',409);await this.db.run("UPDATE server_audio_engine SET status='paused',updated_at=CURRENT_TIMESTAMP WHERE id=1");await this.event('paused','Reproducción de prueba pausada.');return this.status();}
  async resume(){const state=await this.row();if(state.status!=='paused')throw new ServerAudioError('El motor no está pausado.',409);await this.db.run("UPDATE server_audio_engine SET status='playing',last_heartbeat_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=1");await this.event('resumed','Reproducción de prueba reanudada.');return this.status();}
  async stop(reason='operator_stop'){const state=await this.row();if(state.active_queue_id)await this.db.run("UPDATE server_audio_sessions SET status='stopped',ended_at=CURRENT_TIMESTAMP,stop_reason=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",[reason,state.active_queue_id]);await this.db.run("UPDATE server_audio_engine SET mode='standby',status='standby',active_source=NULL,active_queue_id=NULL,current_item_id=NULL,current_started_at=NULL,current_position_seconds=0,error_message=NULL,process_owner=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=1");await this.event('stopped',`Motor detenido: ${reason}.`);return this.status();}
  async skip(){const state=await this.row();if(!activeStatuses.has(state.status))throw new ServerAudioError('No hay reproducción activa.',409);return this.advance('skipped');}
  async restart(){const state=await this.row();if(!state.current_item_id)throw new ServerAudioError('No hay elemento actual.',409);await this.db.run("UPDATE server_audio_engine SET current_position_seconds=0,status='starting',updated_at=CURRENT_TIMESTAMP WHERE id=1");await this.openCurrent();return this.status();}
  async recover(message='Recuperación solicitada.'){const state=await this.row();if(!state.auto_recovery&&message!=='Recuperación solicitada.')throw new ServerAudioError('La recuperación automática está desactivada.',409);await this.db.run("UPDATE server_audio_engine SET mode='test',status='recovering',error_message=?,process_owner=?,updated_at=CURRENT_TIMESTAMP WHERE id=1",[message,this.owner]);await this.event('recovering',message);if(state.current_item_id){await this.db.run("UPDATE server_audio_engine SET status='starting',updated_at=CURRENT_TIMESTAMP WHERE id=1");await this.openCurrent();}else await this.stop('recovery_without_item');return this.status();}
  async handleItemError(error){const state=await this.row();const item=(await this.db.all('SELECT * FROM server_audio_queue_items WHERE id=?',[state.current_item_id]))[0];if(item)await this.db.run("UPDATE server_audio_queue_items SET status='error',updated_at=CURRENT_TIMESTAMP WHERE id=?",[item.id]);await this.event('item_error',error.message,{queueItemId:item?.id});await this.db.run("UPDATE server_audio_engine SET status='error',error_message=?,updated_at=CURRENT_TIMESTAMP WHERE id=1",[error.message]);if(state.auto_recovery)return this.advance('error');}
  async fail(error){await this.db.run("UPDATE server_audio_engine SET status='error',error_message=?,updated_at=CURRENT_TIMESTAMP WHERE id=1",[error.message]);}
  async finish(reason){const state=await this.row();if(state.active_queue_id)await this.db.run("UPDATE server_audio_sessions SET status='completed',ended_at=CURRENT_TIMESTAMP,stop_reason=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",[reason,state.active_queue_id]);await this.db.run("UPDATE server_audio_engine SET status='standby',mode='standby',current_item_id=NULL,current_position_seconds=0,current_started_at=NULL,process_owner=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=1");await this.event('queue_complete','La cola de prueba finalizó.');return this.status();}
  async updateConfig(input={}){const state=await this.row();const enabled=input.watchdogEnabled===undefined?state.watchdog_enabled:(input.watchdogEnabled?1:0),recovery=input.autoRecovery===undefined?state.auto_recovery:(input.autoRecovery?1:0),silence=Number(input.silenceTimeoutSeconds??state.silence_timeout_seconds);if(!Number.isFinite(silence)||silence<5||silence>600)throw new ServerAudioError('El timeout de silencio debe estar entre 5 y 600 segundos.');await this.db.run('UPDATE server_audio_engine SET watchdog_enabled=?,auto_recovery=?,silence_timeout_seconds=?,updated_at=CURRENT_TIMESTAMP WHERE id=1',[enabled,recovery,silence]);return this.config();}
  async volume(value){const number=Number(value);if(!Number.isFinite(number)||number<0||number>1)throw new ServerAudioError('El volumen debe estar entre 0 y 1.');await this.db.run('UPDATE server_audio_engine SET master_volume=?,updated_at=CURRENT_TIMESTAMP WHERE id=1',[number]);return this.status();}
  async crossfade(value){const number=Number(value);if(!Number.isFinite(number)||number<0||number>30)throw new ServerAudioError('El crossfade debe estar entre 0 y 30 segundos.');await this.db.run('UPDATE server_audio_engine SET crossfade_seconds=?,updated_at=CURRENT_TIMESTAMP WHERE id=1',[number]);return this.status();}
  async schedulerCheck(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Panama',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(this.now());const get=t=>parts.find(p=>p.type===t)?.value;const day=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].indexOf(get('weekday')),time=`${get('hour')}:${get('minute')}`;const block=(await this.db.all('SELECT id,name FROM schedule_blocks WHERE active=1 AND day_of_week=? AND start_time<=? AND end_time>? ORDER BY start_time LIMIT 1',[day,time,time]))[0];const key=block?String(block.id):'';if(key&&key!==this.lastSchedulerKey){this.lastSchedulerKey=key;await this.event('schedule_detected',`Bloque activo detectado: ${block.name}. No se tomó control por estar en modo seguro.`,{blockId:block.id});}}
  async event(type,message,metadata={}){const state=await this.row();await this.db.run('INSERT INTO server_audio_events (session_id,queue_item_id,event_type,message,metadata_json) VALUES (?,?,?,?,?)',[state.active_queue_id,metadata.queueItemId||null,type,message,JSON.stringify(metadata)]);}
}
