import { Router } from 'express';
import { all,run } from '../database.js';
import { azuraCastService } from '../services/AzuraCastService.js';
import { DiagnosticAudioAdapter,ServerAudioEngineService } from '../services/ServerAudioEngineService.js';
export const serverAudioService=new ServerAudioEngineService({all,run},{adapter:new DiagnosticAudioAdapter({mediaProvider:(id,range)=>azuraCastService.getMediaAudio(id,range)})});
export const serverAudioRouter=Router();
const handle=(action,status=200)=>async(req,res)=>{try{res.status(status).json(await action(req));}catch(error){res.status(error.status||500).json({error:error.message||'Error interno del motor de audio.'})}};
serverAudioRouter.get('/status',handle(()=>serverAudioService.status()));
serverAudioRouter.get('/current',handle(()=>serverAudioService.current()));
serverAudioRouter.get('/events',handle(req=>serverAudioService.events(req.query.limit)));
serverAudioRouter.get('/config',handle(()=>serverAudioService.config()));
serverAudioRouter.post('/start-test',handle(req=>serverAudioService.start({...req.body,mode:'test'}),201));
serverAudioRouter.post('/start-preview',handle(req=>serverAudioService.start({...req.body,mode:'preview'}),201));
serverAudioRouter.post('/pause',handle(()=>serverAudioService.pause()));
serverAudioRouter.post('/resume',handle(()=>serverAudioService.resume()));
serverAudioRouter.post('/stop',handle(()=>serverAudioService.stop('emergency_stop')));
serverAudioRouter.post('/skip',handle(()=>serverAudioService.skip()));
serverAudioRouter.post('/restart-current',handle(()=>serverAudioService.restart()));
serverAudioRouter.post('/recover',handle(()=>serverAudioService.recover()));
serverAudioRouter.patch('/config',handle(req=>serverAudioService.updateConfig(req.body)));
serverAudioRouter.patch('/volume',handle(req=>serverAudioService.volume(req.body.volume)));
serverAudioRouter.patch('/crossfade',handle(req=>serverAudioService.crossfade(req.body.seconds)));
