export class CartwallPlayback {
  constructor({createAudio=(url)=>new Audio(url),maxConcurrent=3,onChange=()=>{},onError=()=>{}}={}){this.createAudio=createAudio;this.maxConcurrent=maxConcurrent;this.onChange=onChange;this.onError=onError;this.players=new Map();}
  setLimit(value){this.maxConcurrent=Math.max(1,Number(value)||1);}
  snapshot(){return[...this.players.entries()].map(([id,state])=>({id,audio:state.audio,button:state.button}));}
  play(button){if(!button.active||!button.audioUrl)throw new Error('Configura una URL de audio y activa el cartucho.');let source;try{source=new URL(button.audioUrl,globalThis.location?.href).toString();}catch{throw new Error('La URL de audio no es válida.');}if(!source.startsWith('https://')&&globalThis.location?.protocol==='https:')throw new Error('El navegador bloqueó audio HTTP dentro de una página HTTPS.');if(!button.allowOverlap)this.stop(button.id);if(this.players.size>=this.maxConcurrent)throw new Error(`Máximo de ${this.maxConcurrent} reproducciones simultáneas.`);const audio=this.createAudio(source);audio.preload='auto';audio.volume=button.volume;audio.loop=button.loop;const key=button.allowOverlap?`${button.id}-${Date.now()}-${Math.random()}`:button.id;const finish=()=>{this.players.delete(key);this.onChange(this.snapshot());};const fail=()=>{const code=audio.error?.code||'desconocido',message=audio.error?.message||'No se pudo cargar o decodificar el audio.';console.error('[Cartuchera] audio.error',{src:audio.src||source,error:audio.error});this.onError(`Error de audio (${code}): ${message}`);finish();};audio.addEventListener?.('canplay',()=>console.info('[Cartuchera] canplay',{src:audio.src||source}),{once:true});audio.addEventListener?.('play',()=>console.info('[Cartuchera] play',{src:audio.src||source}),{once:true});audio.addEventListener?.('ended',finish,{once:true});audio.addEventListener?.('error',fail,{once:true});this.players.set(key,{audio,button});console.info('[Cartuchera] audio.src',audio.src||source);const promise=audio.play();promise?.catch?.(error=>{this.onError(`El navegador rechazó la reproducción: ${error.message}`);finish();});this.onChange(this.snapshot());return audio;}
  pause(id){for(const[key,state]of this.players)if(state.button.id===id){state.audio.pause();this.onChange(this.snapshot());return key;}}
  restart(id){for(const state of this.players.values())if(state.button.id===id){state.audio.currentTime=0;state.audio.play();this.onChange(this.snapshot());return;}}
  stop(id){for(const[key,state]of[...this.players])if(state.button.id===id){state.audio.pause();state.audio.currentTime=0;this.players.delete(key);}this.onChange(this.snapshot());}
  stopAll(){for(const state of this.players.values()){state.audio.pause();state.audio.currentTime=0;}this.players.clear();this.onChange([]);}
}
